import { ChangeDetectionStrategy, Component, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { Meta, Title } from '@angular/platform-browser';
import { ActivatedRoute, Router } from '@angular/router';
import { finalize, forkJoin } from 'rxjs';
import InfographicCardComponent from '../../components/infographic-card/infographic-card.component';
import { Category, DifficultyLevel, InfographicListItem, Tag } from '../../data-access/infographic.models';
import { InfographicsApiService } from '../../data-access/infographics-api.service';

@Component({selector:'app-visual-handbook-list',imports:[InfographicCardComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<header class="relative overflow-hidden bg-slate-950 text-white"><div class="pointer-events-none absolute inset-0 opacity-25" aria-hidden="true" style="background-image:linear-gradient(rgba(124,58,237,.3) 1px,transparent 1px),linear-gradient(90deg,rgba(124,58,237,.3) 1px,transparent 1px);background-size:48px 48px"></div><div class="relative mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24 lg:px-8"><p class="text-sm font-bold uppercase tracking-[.22em] text-violet-300">Visual Handbook</p><h1 class="mt-4 max-w-4xl text-4xl font-black tracking-tight sm:text-6xl">Practical visual guides for software engineers.</h1><p class="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Explore clear, structured explanations of .NET, Angular, OutSystems, architecture, APIs, and SQL—built for practical engineering work.</p><div class="mt-8 flex flex-wrap gap-3 text-sm text-slate-300"><span class="rounded-full border border-white/15 px-3 py-1.5">Persisted content</span><span class="rounded-full border border-white/15 px-3 py-1.5">Focused steps</span><span class="rounded-full border border-white/15 px-3 py-1.5">Useful resources</span></div></div></header>
<main class="mx-auto max-w-7xl px-4 py-10 sm:px-6 sm:py-14 lg:px-8"><section aria-label="Visual Handbook filters" class="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-2 xl:grid-cols-[minmax(220px,1fr)_180px_170px_170px_150px_auto]"><label><span class="sr-only">Search guides</span><input class="min-h-12 w-full rounded-xl border border-slate-200 px-4 focus:border-violet-500 focus:outline-none focus:ring-2 focus:ring-violet-200" placeholder="Search visual guides" [value]="search()" (input)="search.set($any($event.target).value)" (keyup.enter)="apply()"></label><select class="min-h-12 rounded-xl border border-slate-200 px-4" aria-label="Category" [value]="category()" (change)="category.set($any($event.target).value);apply()"><option value="">All categories</option>@for(item of categories();track item.id){<option [value]="item.slug">{{item.name}}</option>}</select><select class="min-h-12 rounded-xl border border-slate-200 px-4" aria-label="Tag" [value]="tag()" (change)="tag.set($any($event.target).value);apply()"><option value="">All tags</option>@for(item of tags();track item.id){<option [value]="item.slug">{{item.name}}</option>}</select><select class="min-h-12 rounded-xl border border-slate-200 px-4" aria-label="Difficulty" [value]="difficulty()" (change)="difficulty.set($any($event.target).value);apply()"><option value="">All levels</option><option value="1">Beginner</option><option value="2">Intermediate</option><option value="3">Advanced</option></select><select class="min-h-12 rounded-xl border border-slate-200 px-4" aria-label="Sort" [value]="sort()" (change)="sort.set($any($event.target).value);apply()"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="title">Title</option></select><button class="min-h-12 rounded-xl bg-violet-700 px-5 font-bold text-white hover:bg-violet-800" (click)="apply()">Apply</button></section>
@if(loading()){<section class="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3" aria-label="Loading visual guides">@for(item of [1,2,3,4,5,6];track item){<div class="h-[430px] animate-pulse rounded-[20px] bg-slate-200"></div>}</section>}
@else if(error()){<section class="mt-8 rounded-2xl border border-red-200 bg-red-50 p-12 text-center"><h2 class="text-xl font-bold text-red-900">Visual Handbook is temporarily unavailable</h2><p class="mt-2 text-red-700">{{error()}}</p><button class="mt-5 min-h-11 rounded-xl border border-red-300 px-5 font-bold text-red-800" (click)="load()">Try again</button></section>}
@else if(!items().length){<section class="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center"><h2 class="text-xl font-bold">No matching infographics</h2><p class="mt-2 text-slate-600">Try a broader search or clear the current filters.</p><button class="mt-5 min-h-11 rounded-xl bg-violet-700 px-5 font-bold text-white" (click)="clear()">Clear filters</button></section>}
@else{<section class="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3" aria-label="Published infographics">@for(item of items();track item.id){<app-infographic-card [item]="item"/>}</section><nav class="mt-10 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between" aria-label="Visual Handbook pagination"><p class="text-sm text-slate-600">Page {{page()}} of {{totalPages()||1}}</p><div class="flex gap-2"><button class="min-h-11 rounded-xl border border-slate-200 bg-white px-4 font-bold disabled:opacity-40" [disabled]="page()<=1" (click)="changePage(page()-1)">Previous</button><button class="min-h-11 rounded-xl border border-slate-200 bg-white px-4 font-bold disabled:opacity-40" [disabled]="page()>=totalPages()" (click)="changePage(page()+1)">Next</button></div></nav>}
</main>`})
export default class VisualHandbookListComponent{
  private readonly api=inject(InfographicsApiService);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly destroyRef=inject(DestroyRef);private readonly title=inject(Title);private readonly meta=inject(Meta);readonly items=signal<InfographicListItem[]>([]);readonly categories=signal<Category[]>([]);readonly tags=signal<Tag[]>([]);readonly search=signal('');readonly category=signal('');readonly tag=signal('');readonly difficulty=signal('');readonly sort=signal('newest');readonly page=signal(1);readonly totalPages=signal(0);readonly loading=signal(true);readonly error=signal<string|null>(null);
  constructor(){this.title.setTitle('Visual Handbook | Sultan Alomran');this.meta.updateTag({name:'description',content:'Practical visual guides for .NET, Angular, OutSystems, architecture, APIs, SQL, and software engineering.'});forkJoin({categories:this.api.categories(),tags:this.api.tags()}).pipe(takeUntilDestroyed()).subscribe({next:x=>{this.categories.set(x.categories);this.tags.set(x.tags)}});this.route.queryParamMap.pipe(takeUntilDestroyed()).subscribe(params=>{this.search.set(params.get('search')||'');this.category.set(params.get('category')||'');this.tag.set(params.get('tag')||'');this.difficulty.set(params.get('difficulty')||'');this.sort.set(params.get('sort')||'newest');this.page.set(Math.max(1,Number(params.get('page'))||1));this.load()})}
  load(){this.loading.set(true);this.error.set(null);this.api.list({search:this.search(),category:this.category(),tag:this.tag(),difficulty:this.difficulty()===''?undefined:Number(this.difficulty()) as DifficultyLevel,sort:this.sort(),page:this.page(),pageSize:9}).pipe(finalize(()=>this.loading.set(false)),takeUntilDestroyed(this.destroyRef)).subscribe({next:r=>{this.items.set(r.items);this.totalPages.set(r.totalPages)},error:()=>this.error.set('Check your connection and try again.')})}
  apply(){this.navigate(1)}changePage(page:number){this.navigate(page)}clear(){this.search.set('');this.category.set('');this.tag.set('');this.difficulty.set('');this.sort.set('newest');this.navigate(1)}private navigate(page:number){this.router.navigate([],{relativeTo:this.route,queryParams:{search:this.search()||null,category:this.category()||null,tag:this.tag()||null,difficulty:this.difficulty()||null,sort:this.sort()==='newest'?null:this.sort(),page:page===1?null:page}})}
}
