import { DatePipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, DestroyRef, HostListener, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { AdminEmptyStateComponent } from '../../../../shared/components/admin-empty-state/admin-empty-state.component';
import { AdminLoadingSkeletonComponent } from '../../../../shared/components/admin-loading-skeleton/admin-loading-skeleton.component';
import { AdminPageHeaderComponent } from '../../../../shared/components/admin-page-header/admin-page-header.component';
import { TestAnalyticsApiService } from '../../data-access/test-analytics-api.service';
import { TestArtifact, TestRunDetails, artifactTypeLabel, availabilityLabel, caseStatusLabel, durationLabel, modeLabel, runStatusLabel } from '../../data-access/test-analytics.models';

@Component({
  selector: 'app-test-run-details',
  imports: [DatePipe, RouterLink, AdminPageHeaderComponent, AdminEmptyStateComponent, AdminLoadingSkeletonComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: [`
    .quality-filter { border: 1px solid hsl(var(--border)); background: hsl(var(--background)); color: hsl(var(--foreground)); }
    .quality-filter:hover { border-color: hsl(var(--primary) / .55); background: hsl(var(--primary) / .08); color: hsl(var(--primary)); }
    .quality-filter:focus-visible, .quality-action:focus-visible { outline: 2px solid hsl(var(--primary)); outline-offset: 2px; }
    .quality-filter-active { border-color: hsl(var(--primary)); background: hsl(var(--primary)); color: hsl(var(--primary-foreground)); }
    .quality-filter-active:hover { background: hsl(var(--primary) / .9); color: hsl(var(--primary-foreground)); }
    .quality-action { display:inline-flex; min-height:2.25rem; align-items:center; justify-content:center; gap:.4rem; border-radius:.625rem; padding:.45rem .75rem; font-size:.75rem; font-weight:600; transition:background-color .15s,color .15s,border-color .15s; }
    .quality-action:disabled { cursor:not-allowed; opacity:.5; }
    .quality-action-primary { border:1px solid hsl(var(--primary)); background:hsl(var(--primary)); color:hsl(var(--primary-foreground)); }
    .quality-action-primary:hover { background:hsl(var(--primary) / .88); }
    .quality-action-secondary { border:1px solid hsl(var(--primary) / .45); background:hsl(var(--primary) / .1); color:hsl(var(--primary)); }
    .quality-action-secondary:hover { border-color:hsl(var(--primary)); background:hsl(var(--primary) / .16); }
    .quality-action-utility { border:1px solid hsl(var(--border)); background:hsl(var(--muted) / .55); color:hsl(var(--foreground)); }
    .quality-action-utility:hover { border-color:hsl(var(--primary) / .45); background:hsl(var(--muted)); }
  `],
  template: `
<app-admin-page-header [title]="details()?'Run #'+details()!.run.providerRunId:'Test Run'" description="Inspect test results, failures and evidence metadata." [breadcrumbs]="[{label:'Quality'},{label:'Test Analytics',link:'/quality/tests'},{label:'Run details'}]"><a adminPageActions routerLink="/quality/tests" class="kt-btn kt-btn-outline"><i class="ki-filled ki-arrow-left"></i>All runs</a></app-admin-page-header>
@if(loading()){<section class="rounded-[20px] border border-border bg-background p-6"><app-admin-loading-skeleton [rows]="8"/></section>}@else if(error()){<section class="rounded-[20px] border border-red-200 bg-red-50 p-10 text-center dark:border-red-900/50 dark:bg-red-950/20"><h2 class="font-semibold">Run could not be loaded</h2><p class="mt-2 text-sm text-muted-foreground">{{error()}}</p><button class="kt-btn kt-btn-outline mt-4" (click)="load()">Retry</button></section>}@else if(details();as data){
<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article class="rounded-[20px] border border-border bg-background p-5"><span class="text-xs text-muted-foreground">Status</span><strong class="mt-2 block text-xl">{{runStatus(data.run.status)}}</strong></article><article class="rounded-[20px] border border-border bg-background p-5"><span class="text-xs text-muted-foreground">Mode</span><strong class="mt-2 block text-xl">{{mode(data.run.executionMode)}}</strong></article><article class="rounded-[20px] border border-border bg-background p-5"><span class="text-xs text-muted-foreground">Duration</span><strong class="mt-2 block text-xl">{{duration(data.run.durationMs)}}</strong></article><article class="rounded-[20px] border border-border bg-background p-5"><span class="text-xs text-muted-foreground">Artifacts</span><strong class="mt-2 block text-xl">{{data.artifacts.length}}</strong></article></section>
<section class="mt-5 grid gap-5 xl:grid-cols-[.7fr_1.3fr]"><article class="rounded-[20px] border border-border bg-background p-5 shadow-sm"><h2 class="font-semibold">Run context</h2><dl class="mt-4 grid grid-cols-[auto_1fr] gap-x-4 gap-y-3 text-sm"><dt class="text-muted-foreground">Workflow</dt><dd>{{data.workflowName}} @if(data.workflowRunNumber){#{{data.workflowRunNumber}}}</dd><dt class="text-muted-foreground">Branch</dt><dd>{{data.run.branch}}</dd><dt class="text-muted-foreground">Commit</dt><dd class="font-mono">{{data.run.commitSha.slice(0,12)}}</dd><dt class="text-muted-foreground">Pull request</dt><dd>{{data.run.pullRequestNumber?'#'+data.run.pullRequestNumber:'â€”'}}</dd><dt class="text-muted-foreground">Trigger</dt><dd>{{data.run.trigger}}</dd><dt class="text-muted-foreground">Browsers</dt><dd>{{data.run.browserSummary||'Not recorded'}}</dd><dt class="text-muted-foreground">Features</dt><dd>{{data.featureSummary||'Not recorded'}}</dd><dt class="text-muted-foreground">Started</dt><dd>{{data.run.startedAtUtc|date:'medium'}}</dd></dl><div class="mt-5 flex flex-wrap gap-2">@if(data.run.workflowRunUrl){<a class="quality-action quality-action-utility" [href]="data.run.workflowRunUrl" target="_blank" rel="noopener">Open GitHub run <i class="ki-filled ki-exit-right-corner"></i></a>}@if(data.pullRequestUrl){<a class="quality-action quality-action-utility" [href]="data.pullRequestUrl" target="_blank" rel="noopener">Open PR</a>}</div></article>
<article class="rounded-[20px] border border-border bg-background p-5 shadow-sm"><h2 class="font-semibold">Result summary</h2><div class="mt-4 grid gap-3 sm:grid-cols-4"><div class="rounded-xl bg-emerald-50 p-4 dark:bg-emerald-950/30"><strong class="text-2xl text-emerald-700 dark:text-emerald-300">{{data.run.passedCount}}</strong><span class="block text-xs text-muted-foreground">Passed</span></div><div class="rounded-xl bg-red-50 p-4 dark:bg-red-950/30"><strong class="text-2xl text-red-700 dark:text-red-300">{{data.run.failedCount}}</strong><span class="block text-xs text-muted-foreground">Failed</span></div><div class="rounded-xl bg-muted p-4"><strong class="text-2xl">{{data.run.skippedCount}}</strong><span class="block text-xs text-muted-foreground">Skipped</span></div><div class="rounded-xl bg-amber-50 p-4 dark:bg-amber-950/30"><strong class="text-2xl text-amber-700 dark:text-amber-300">{{data.run.flakyCount}}</strong><span class="block text-xs text-muted-foreground">Flaky</span></div></div></article></section>

<section class="mt-5 rounded-[20px] border border-border bg-background shadow-sm"><div class="border-b border-border p-5"><h2 class="font-semibold">Test-case results</h2><p class="text-xs text-muted-foreground">Failures and flaky results are prioritized.</p></div>@if(!data.tests.length){<div class="p-6"><app-admin-empty-state title="No case results" description="This run contains metadata but no imported test cases." icon="ki-document"/></div>}@else{<div class="overflow-x-auto"><table class="w-full min-w-[900px] text-sm"><thead class="border-b border-border bg-muted/40 text-xs uppercase text-muted-foreground"><tr><th class="p-4 text-start">Test</th><th class="p-4 text-start">Feature</th><th class="p-4 text-start">Browser</th><th class="p-4 text-start">Status</th><th class="p-4 text-start">Duration</th><th class="p-4 text-start">Retries</th></tr></thead><tbody>@for(test of data.tests;track test.id){<tr class="border-b border-border last:border-0 align-top"><td class="p-4"><strong>{{test.testName}}</strong><p class="text-xs text-muted-foreground">{{test.suite}}</p>@if(test.errorSummary){<details class="mt-2"><summary class="cursor-pointer text-xs font-medium text-red-600">Error summary</summary><pre class="mt-2 max-w-2xl whitespace-pre-wrap rounded-lg bg-red-50 p-3 text-xs text-red-800 dark:bg-red-950/30 dark:text-red-200">{{test.errorSummary}}</pre></details>}</td><td class="p-4">{{test.feature}}</td><td class="p-4">{{test.browser}} @if(test.viewport){<span class="block text-xs text-muted-foreground">{{test.viewport}}</span>}</td><td class="p-4"><span class="rounded-full px-2 py-1 text-xs" [class]="caseClass(test.status)">{{caseStatus(test.status)}} @if(test.isFlaky){آ· flaky}</span></td><td class="p-4">{{duration(test.durationMs)}}</td><td class="p-4">{{test.retryCount}}</td></tr>}</tbody></table></div>}</section>

<section class="mt-5 rounded-[20px] border border-border bg-background p-5 shadow-sm" data-testid="quality-artifacts"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-semibold">Artifacts</h2><p class="text-xs text-muted-foreground">Evidence binaries stay in local/GitHub artifact storage; SQL stores metadata only.</p></div><div class="flex flex-wrap gap-2" aria-label="Artifact filters">@for(filter of artifactFilters;track filter.value){<button type="button" class="kt-btn kt-btn-sm quality-filter" [class.quality-filter-active]="artifactFilter()===filter.value" [attr.aria-pressed]="artifactFilter()===filter.value" (click)="artifactFilter.set(filter.value)">{{filter.label}}</button>}</div></div>
@if(!filteredArtifacts(data.artifacts).length){<div class="mt-5"><app-admin-empty-state title="No artifacts in this view" description="Evidence may not have been produced for this execution mode." icon="ki-folder"/></div>}@else{<div class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">@for(item of filteredArtifacts(data.artifacts);track item.id){<article class="overflow-hidden rounded-2xl border border-border bg-background" [attr.data-artifact-type]="item.artifactType">
  @if(isScreenshot(item)&&item.availabilityStatus===0&&!unavailable()[item.id]){<button type="button" class="block aspect-video w-full overflow-hidden border-b border-border bg-muted text-start" (click)="openPreview(item)" [attr.aria-label]="'Preview '+item.name"><img class="h-full w-full object-cover" [src]="api.previewUrl(item.id)" [alt]="'Screenshot preview: '+item.name" loading="lazy" (error)="markUnavailable(item)"/></button>}@else{<div class="grid aspect-video place-items-center border-b border-border bg-muted/50"><div class="grid size-14 place-items-center rounded-2xl bg-primary/10 text-2xl text-primary"><i class="ki-filled" [class]="artifactIcon(item.artifactType)"></i></div></div>}
  <div class="p-4"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><strong class="block truncate" [title]="item.name">{{item.name}}</strong><p class="mt-1 text-xs text-muted-foreground">{{artifactType(item.artifactType)}} آ· {{item.browser||'Browser not recorded'}}</p></div><span class="shrink-0 rounded-full px-2 py-1 text-[11px]" [class]="availabilityClass(effectiveAvailability(item))">{{availability(effectiveAvailability(item))}}</span></div>
  <dl class="mt-3 grid grid-cols-[auto_1fr] gap-x-3 gap-y-1 text-xs"><dt class="text-muted-foreground">Test</dt><dd class="truncate">{{testLabel(data,item)}}</dd><dt class="text-muted-foreground">Feature</dt><dd>{{item.feature||'Not recorded'}}</dd><dt class="text-muted-foreground">Size</dt><dd>{{fileSize(item.sizeBytes)}}</dd><dt class="text-muted-foreground">Preview</dt><dd>{{isPreviewable(item)?'Available':'Not supported'}}</dd></dl>
  @if(item.expiresAtUtc&&effectiveAvailability(item)===0){<p class="mt-2 text-xs text-amber-700 dark:text-amber-300">Available until {{item.expiresAtUtc|date:'mediumDate'}}</p>}@if(effectiveAvailability(item)!==0){<p class="mt-2 text-xs text-muted-foreground">Preview is no longer available for this artifact.</p>}
  <div class="mt-4 flex flex-wrap gap-2">@if(isPreviewable(item)&&effectiveAvailability(item)===0){<button type="button" class="quality-action quality-action-primary" (click)="openPreview(item)"><i class="ki-filled ki-eye"></i>Preview</button>}@if(effectiveAvailability(item)===0){<a class="quality-action quality-action-secondary" [href]="api.downloadUrl(item.id)"><i class="ki-filled ki-cloud-download"></i>{{item.artifactType===3?'Download trace':'Download'}}</a>}@if(item.externalUrl){<a class="quality-action quality-action-utility" [href]="item.externalUrl" target="_blank" rel="noopener">Details <i class="ki-filled ki-exit-right-corner"></i></a>}</div></div>
</article>}</div>}</section>
}

@if(previewArtifact();as preview){<div class="fixed inset-0 z-[100] grid place-items-center overflow-y-auto p-3 sm:p-6"><button type="button" class="absolute inset-0 size-full cursor-default bg-black/70" aria-label="Close artifact preview" (click)="closePreview()"></button><section class="relative max-h-[94vh] w-full max-w-6xl overflow-auto rounded-2xl border border-border bg-background p-4 shadow-2xl sm:p-6" role="dialog" aria-modal="true" [attr.aria-label]="'Artifact preview: '+preview.name"><header class="mb-4 flex items-start justify-between gap-3"><div class="min-w-0"><h2 class="truncate font-semibold">{{preview.name}}</h2><p class="text-xs text-muted-foreground">{{artifactType(preview.artifactType)}} preview</p></div><button #closeButton type="button" class="quality-action quality-action-utility shrink-0" aria-label="Close preview" (click)="closePreview()"><i class="ki-filled ki-cross"></i>Close</button></header>
@if(previewError()){<div class="rounded-xl border border-amber-300 bg-amber-50 p-6 text-center text-sm text-amber-900 dark:border-amber-800 dark:bg-amber-950/30 dark:text-amber-100">Preview is no longer available for this artifact.<div class="mt-4"><a class="quality-action quality-action-secondary" [href]="api.downloadUrl(preview.id)">Download artifact</a></div></div>}@else if(isScreenshot(preview)){<img class="mx-auto max-h-[calc(94vh-8rem)] max-w-full rounded-xl object-contain" [src]="api.previewUrl(preview.id)" [alt]="preview.name" (error)="previewError.set(true)"/>}@else{<video class="mx-auto aspect-video max-h-[calc(94vh-8rem)] w-full rounded-xl bg-black" controls preload="metadata" [src]="api.previewUrl(preview.id)" (error)="previewError.set(true)">Your browser cannot play this recording.</video>}
</section></div>}
  `
})
export default class TestRunDetailsComponent {
  readonly api = inject(TestAnalyticsApiService);
  private readonly route = inject(ActivatedRoute);
  private readonly destroyRef = inject(DestroyRef);
  readonly details = signal<TestRunDetails | null>(null);
  readonly loading = signal(true);
  readonly error = signal<string | null>(null);
  readonly artifactFilter = signal<number | 'all'>('all');
  readonly previewArtifact = signal<TestArtifact | null>(null);
  readonly previewError = signal(false);
  readonly unavailable = signal<Record<string, boolean>>({});
  readonly runStatus = runStatusLabel;
  readonly mode = modeLabel;
  readonly duration = durationLabel;
  readonly caseStatus = caseStatusLabel;
  readonly artifactType = artifactTypeLabel;
  readonly availability = availabilityLabel;
  readonly artifactFilters = [{ label: 'All', value: 'all' as const }, { label: 'Screenshots', value: 1 }, { label: 'Videos', value: 2 }, { label: 'Traces', value: 3 }, { label: 'Reports', value: 0 }];

  constructor() { this.load(); }
  @HostListener('document:keydown.escape') onEscape() { this.closePreview(); }
  load() { this.loading.set(true); this.error.set(null); this.api.run(this.route.snapshot.paramMap.get('id')!).pipe(finalize(() => this.loading.set(false)), takeUntilDestroyed(this.destroyRef)).subscribe({ next: value => this.details.set(value), error: error => this.error.set(error.status === 404 ? 'This test run does not exist.' : error?.error?.detail ?? 'Check that Portfolio.Api is running.') }); }
  filteredArtifacts(items: TestArtifact[]) { const filter = this.artifactFilter(); return filter === 'all' ? items : filter === 0 ? items.filter(x => [0, 4, 5].includes(x.artifactType)) : items.filter(x => x.artifactType === filter); }
  openPreview(item: TestArtifact) { this.previewError.set(false); this.previewArtifact.set(item); queueMicrotask(() => (document.querySelector('[aria-label="Close preview"]') as HTMLElement | null)?.focus()); }
  closePreview() { this.previewArtifact.set(null); this.previewError.set(false); }
  markUnavailable(item: TestArtifact) { this.unavailable.update(value => ({ ...value, [item.id]: true })); }
  effectiveAvailability(item: TestArtifact) { return this.unavailable()[item.id] ? 2 : item.availabilityStatus; }
  isScreenshot(item: TestArtifact) { return item.artifactType === 1 && ['image/png', 'image/jpeg', 'image/webp'].includes(item.mimeType ?? ''); }
  isPreviewable(item: TestArtifact) { return this.isScreenshot(item) || (item.artifactType === 2 && ['video/webm', 'video/mp4'].includes(item.mimeType ?? '')); }
  testLabel(data: TestRunDetails, item: TestArtifact) { return data.tests.find(test => test.id === item.testCaseResultId)?.testName ?? 'Run-level evidence'; }
  fileSize(bytes: number | null) { if (bytes == null) return 'Not recorded'; const units = ['B', 'KB', 'MB', 'GB']; let value = bytes; let unit = 0; while (value >= 1024 && unit < units.length - 1) { value /= 1024; unit++; } return `${value.toFixed(unit ? 1 : 0)} ${units[unit]}`; }
  caseClass(status: number) { return status === 0 ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300' : status === 1 ? 'bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-300' : 'bg-muted text-muted-foreground'; }
  availabilityClass(status: number) { return status === 0 ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300' : 'bg-muted text-muted-foreground'; }
  artifactIcon(type: number) { return ['ki-document', 'ki-picture', 'ki-video', 'ki-code', 'ki-document', 'ki-code', 'ki-information', 'ki-folder'][type] ?? 'ki-folder'; }
}
