import { DatePipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { forkJoin, finalize } from 'rxjs';
import { AdminEmptyStateComponent } from '../../../../shared/components/admin-empty-state/admin-empty-state.component';
import { AdminLoadingSkeletonComponent } from '../../../../shared/components/admin-loading-skeleton/admin-loading-skeleton.component';
import { AdminPageHeaderComponent } from '../../../../shared/components/admin-page-header/admin-page-header.component';
import { AdminPaginationComponent } from '../../../../shared/components/admin-pagination/admin-pagination.component';
import { TestAnalyticsApiService } from '../../data-access/test-analytics-api.service';
import { DashboardOverview, PagedResult, TestAnalyticsQuery, TestRunSummary, durationLabel, modeLabel, runStatusLabel } from '../../data-access/test-analytics.models';

@Component({
 selector:'app-test-analytics-dashboard',
 imports:[DatePipe,RouterLink,AdminPageHeaderComponent,AdminEmptyStateComponent,AdminLoadingSkeletonComponent,AdminPaginationComponent],
 changeDetection:ChangeDetectionStrategy.OnPush,
 template:`
 <app-admin-page-header title="Test Analytics" description="Permanent engineering-quality telemetry for Playwright and CI." [breadcrumbs]="[{label:'Quality'},{label:'Test Analytics'}]">
   <span adminPageActions class="inline-flex items-center gap-2 rounded-full border border-border bg-background px-3 py-2 text-xs text-muted-foreground"><span class="size-2 rounded-full bg-emerald-500"></span>Historical telemetry</span>
 </app-admin-page-header>

 <section class="mb-5 rounded-[20px] border border-border bg-background p-4 shadow-sm" aria-label="Test analytics filters">
  <div class="grid gap-3 md:grid-cols-2 xl:grid-cols-7">
   <label class="text-xs font-medium text-muted-foreground">Range<select class="kt-select mt-1" [value]="range()" (change)="range.set($any($event.target).value)"><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option><option value="all">All</option></select></label>
   <label class="text-xs font-medium text-muted-foreground">Branch<input class="kt-input mt-1" placeholder="All branches" [value]="branch()" (input)="branch.set($any($event.target).value)"></label>
   <label class="text-xs font-medium text-muted-foreground">Feature<input class="kt-input mt-1" placeholder="All features" [value]="feature()" (input)="feature.set($any($event.target).value)"></label>
   <label class="text-xs font-medium text-muted-foreground">Browser<select class="kt-select mt-1" [value]="browser()" (change)="browser.set($any($event.target).value)"><option value="">All browsers</option><option>chromium</option><option>firefox</option><option>webkit</option></select></label>
   <label class="text-xs font-medium text-muted-foreground">Status<select class="kt-select mt-1" [value]="status()" (change)="status.set($any($event.target).value)"><option value="">All statuses</option><option value="1">Passed</option><option value="2">Failed</option><option value="3">Cancelled</option><option value="4">Timed out</option></select></label>
   <label class="text-xs font-medium text-muted-foreground">Mode<select class="kt-select mt-1" [value]="mode()" (change)="mode.set($any($event.target).value)"><option value="">All modes</option><option value="0">Standard</option><option value="1">Visual</option><option value="2">Full recording</option></select></label>
   <div class="flex items-end"><button class="kt-btn kt-btn-primary w-full" type="button" (click)="applyFilters()"><i class="ki-filled ki-filter"></i>Apply filters</button></div>
  </div>
 </section>

 @if(loading()){<section class="rounded-[20px] border border-border bg-background p-6"><app-admin-loading-skeleton [rows]="8"/></section>}
 @else if(error()){<section class="rounded-[20px] border border-red-200 bg-red-50 p-10 text-center dark:border-red-900/50 dark:bg-red-950/20"><i class="ki-filled ki-information-2 text-4xl text-red-500"></i><h2 class="mt-3 text-lg font-semibold">Quality telemetry could not be loaded</h2><p class="mt-2 text-sm text-muted-foreground">{{error()}}</p><button class="kt-btn kt-btn-outline mt-5" (click)="load()">Retry</button></section>}
 @else if(!overview()?.totalRuns){<section class="rounded-[20px] border border-border bg-background p-6"><app-admin-empty-state title="No test history yet" description="Run Playwright, generate telemetry.json, then import it locally. Real history will appear here without fabricated statistics." icon="ki-chart-simple-3"/></section>}
 @else if(overview();as data){
  <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Quality summary">
   @for(card of cards(data);track card.label){<article class="rounded-[20px] border border-border bg-background p-5 shadow-sm"><div class="flex items-center justify-between"><span class="text-sm text-muted-foreground">{{card.label}}</span><i class="ki-filled {{card.icon}} text-lg text-primary"></i></div><strong class="mt-3 block text-2xl tracking-tight">{{card.value}}</strong><span class="mt-1 block text-xs text-muted-foreground">{{card.hint}}</span></article>}
  </section>

  <section class="mt-5 grid gap-5 xl:grid-cols-[1.4fr_.6fr]">
   <article class="rounded-[20px] border border-border bg-background p-5 shadow-sm"><div class="flex items-center justify-between"><div><h2 class="font-semibold">Run health trend</h2><p class="text-xs text-muted-foreground">Passed, failed and flaky tests over time</p></div><span class="text-xs text-muted-foreground">{{data.runTrend.length}} points</span></div>
    <div class="mt-6 flex h-52 items-end gap-2 overflow-x-auto border-b border-border px-1 pb-2" role="img" aria-label="Test health bar chart">@for(point of data.runTrend;track point.date){<div class="flex min-w-8 flex-1 flex-col items-center justify-end gap-1" [title]="(point.date|date:'mediumDate')+': '+point.passed+' passed, '+point.failed+' failed'"><div class="flex w-full items-end justify-center gap-px"><span class="w-2 rounded-t bg-emerald-500" [style.height.px]="bar(point.passed,data)"></span><span class="w-2 rounded-t bg-red-500" [style.height.px]="bar(point.failed,data)"></span><span class="w-2 rounded-t bg-amber-400" [style.height.px]="bar(point.flaky,data)"></span></div><span class="text-[10px] text-muted-foreground">{{point.date|date:'M/d'}}</span></div>}</div>
    <div class="mt-3 flex gap-4 text-xs text-muted-foreground"><span><i class="me-1 inline-block size-2 rounded-full bg-emerald-500"></i>Passed</span><span><i class="me-1 inline-block size-2 rounded-full bg-red-500"></i>Failed</span><span><i class="me-1 inline-block size-2 rounded-full bg-amber-400"></i>Flaky</span></div>
   </article>
   <article class="rounded-[20px] border border-border bg-background p-5 shadow-sm"><h2 class="font-semibold">Browser quality</h2><p class="text-xs text-muted-foreground">Actual recorded coverage</p><div class="mt-4 space-y-4">@for(item of data.browsers;track item.browser){<div><div class="flex items-center justify-between text-sm"><span class="font-medium capitalize">{{item.browser}}</span><strong>{{item.passRate}}%</strong></div><div class="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div class="h-full rounded-full bg-primary" [style.width.%]="item.passRate"></div></div><p class="mt-1 text-xs text-muted-foreground">{{item.tests}} tests · {{duration(item.averageDurationMs)}} avg</p></div>}</div></article>
  </section>

  <section class="mt-5 grid gap-5 xl:grid-cols-2">
   <article class="rounded-[20px] border border-border bg-background p-5 shadow-sm"><h2 class="font-semibold">Vertical-slice coverage</h2><p class="text-xs text-muted-foreground">Derived only from recorded tests</p><div class="mt-4 space-y-3">@for(item of data.features;track item.feature){<div class="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border p-3"><div><strong class="text-sm">{{item.feature}}</strong><p class="text-xs text-muted-foreground">{{item.tests}} tests · {{item.browserCoverage}} browsers · {{item.lastTestedAtUtc|date:'mediumDate'}}</p></div><div class="flex gap-1">@if(item.hasVisualEvidence){<span class="rounded-full bg-violet-100 px-2 py-1 text-[11px] text-violet-700 dark:bg-violet-950 dark:text-violet-300">Visual</span>}@if(item.hasRecording){<span class="rounded-full bg-indigo-100 px-2 py-1 text-[11px] text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300">Recording</span>}</div></div>}</div></article>
   <article class="rounded-[20px] border border-border bg-background p-5 shadow-sm"><h2 class="font-semibold">Execution modes</h2><p class="text-xs text-muted-foreground">Regression and evidence activity</p><div class="mt-4 grid gap-3 sm:grid-cols-3">@for(item of data.executionModes;track item.mode){<div class="rounded-xl bg-muted/50 p-4"><span class="text-xs text-muted-foreground">{{modeName(item.mode)}}</span><strong class="mt-2 block text-xl">{{item.passRate}}%</strong><p class="text-xs text-muted-foreground">{{item.runs}} runs · {{item.artifacts}} artifacts</p></div>}</div></article>
  </section>

  <section class="mt-5 rounded-[20px] border border-border bg-background shadow-sm"><div class="flex items-center justify-between border-b border-border p-5"><div><h2 class="font-semibold">Recent runs</h2><p class="text-xs text-muted-foreground">Commit, branch, mode and evidence context</p></div><span class="text-xs text-muted-foreground">{{runs()?.totalCount}} total</span></div>
   <div class="overflow-x-auto"><table class="w-full min-w-[980px] text-sm"><thead class="border-b border-border bg-muted/40 text-xs uppercase text-muted-foreground"><tr><th class="p-4 text-start">Run</th><th class="p-4 text-start">Status</th><th class="p-4 text-start">Branch / commit</th><th class="p-4 text-start">Mode</th><th class="p-4 text-start">Results</th><th class="p-4 text-start">Duration</th><th class="p-4 text-start">Started</th><th class="p-4 text-end">Actions</th></tr></thead><tbody>@for(run of runs()?.items;track run.id){<tr class="border-b border-border last:border-0 hover:bg-muted/30"><td class="p-4 font-medium">#{{run.providerRunId}}</td><td class="p-4"><span class="rounded-full px-2 py-1 text-xs font-medium" [class]="statusClass(run.status)">{{statusName(run.status)}}</span></td><td class="p-4"><strong class="block max-w-52 truncate">{{run.branch}}</strong><span class="font-mono text-xs text-muted-foreground">{{run.commitSha.slice(0,7)}} @if(run.pullRequestNumber){· PR #{{run.pullRequestNumber}}}</span></td><td class="p-4">{{modeName(run.executionMode)}}</td><td class="p-4"><span class="text-emerald-600">{{run.passedCount}} pass</span> · <span class="text-red-600">{{run.failedCount}} fail</span> · <span class="text-amber-600">{{run.flakyCount}} flaky</span></td><td class="p-4">{{duration(run.durationMs)}}</td><td class="p-4 text-muted-foreground">{{run.startedAtUtc|date:'short'}}</td><td class="p-4 text-end"><a class="kt-btn kt-btn-sm kt-btn-outline" [routerLink]="['/quality/tests/runs',run.id]">View run</a></td></tr>}</tbody></table></div>
   @if(runs();as page){<div class="border-t border-border p-4"><app-admin-pagination [page]="page.page" [pageSize]="page.pageSize" [totalItems]="page.totalCount" (pageChange)="changePage($event)"/></div>}
  </section>

  <section class="mt-5 grid gap-5 xl:grid-cols-2"><article class="rounded-[20px] border border-border bg-background p-5 shadow-sm"><h2 class="font-semibold">Flaky tests</h2>@if(!data.flaky.length){<p class="mt-4 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300">No flaky tests in this filter range.</p>}@else{<div class="mt-3 space-y-3">@for(item of data.flaky.slice(0,6);track item.testName+item.browser){<div class="rounded-xl border border-border p-3"><div class="flex justify-between gap-3"><strong class="text-sm">{{item.testName}}</strong><span class="text-xs font-semibold text-amber-600">{{item.flakyRate}}%</span></div><p class="text-xs text-muted-foreground">{{item.feature}} · {{item.browser}} · {{item.retries}} retries</p></div>}</div>}</article>
   <article class="rounded-[20px] border border-border bg-background p-5 shadow-sm"><h2 class="font-semibold">Slowest tests</h2><div class="mt-3 space-y-3">@for(item of data.slowest.slice(0,6);track item.testName+item.browser){<div class="flex items-center justify-between gap-3 rounded-xl border border-border p-3"><div><strong class="text-sm">{{item.testName}}</strong><p class="text-xs text-muted-foreground">{{item.feature}} · {{item.browser}}</p></div><span class="text-sm font-semibold">{{duration(item.averageDurationMs)}}</span></div>}</div></article></section>
 }
 `
})
export default class TestAnalyticsDashboardComponent{
 private readonly api=inject(TestAnalyticsApiService);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly destroyRef=inject(DestroyRef);
 readonly overview=signal<DashboardOverview|null>(null);readonly runs=signal<PagedResult<TestRunSummary>|null>(null);readonly loading=signal(true);readonly error=signal<string|null>(null);
 readonly range=signal(this.route.snapshot.queryParamMap.get('range')??'30');readonly branch=signal(this.route.snapshot.queryParamMap.get('branch')??'');readonly feature=signal(this.route.snapshot.queryParamMap.get('feature')??'');readonly browser=signal(this.route.snapshot.queryParamMap.get('browser')??'');readonly status=signal(this.route.snapshot.queryParamMap.get('status')??'');readonly mode=signal(this.route.snapshot.queryParamMap.get('mode')??'');
 readonly duration=durationLabel;readonly modeName=modeLabel;readonly statusName=runStatusLabel;
 constructor(){this.load();}
 query(page=Number(this.route.snapshot.queryParamMap.get('page')??1)):TestAnalyticsQuery{const days=this.range()==='all'?undefined:Number(this.range());const from=days?new Date(Date.now()-days*86400000).toISOString():undefined;return{from,branch:this.branch()||undefined,feature:this.feature()||undefined,browser:this.browser()||undefined,status:this.status()===''?undefined:Number(this.status()) as 0|1|2|3|4,executionMode:this.mode()===''?undefined:Number(this.mode()) as 0|1|2,page,pageSize:10};}
 load(page?:number){this.loading.set(true);this.error.set(null);const query=this.query(page);forkJoin({overview:this.api.overview(query),runs:this.api.runs(query)}).pipe(finalize(()=>this.loading.set(false)),takeUntilDestroyed(this.destroyRef)).subscribe({next:value=>{this.overview.set(value.overview);this.runs.set(value.runs);},error:error=>this.error.set(error?.error?.detail??'Check that Portfolio.Api and the local database are running.')});}
 applyFilters(){this.router.navigate([], {relativeTo:this.route,queryParams:{range:this.range(),branch:this.branch()||null,feature:this.feature()||null,browser:this.browser()||null,status:this.status()||null,mode:this.mode()||null,page:1}}).then(()=>this.load(1));}
 changePage(page:number){this.router.navigate([], {relativeTo:this.route,queryParams:{page},queryParamsHandling:'merge'}).then(()=>this.load(page));}
 cards(d:DashboardOverview){return[{label:'Pass rate',value:`${d.passRate}%`,hint:'Passed / decided tests',icon:'ki-chart-line-up'},{label:'Total runs',value:d.totalRuns,hint:`${d.testsExecuted} tests executed`,icon:'ki-chart'},{label:'Failed tests',value:d.failedTests,hint:'Across selected history',icon:'ki-information-2'},{label:'Flaky tests',value:d.flakyTests,hint:'Retries and unstable results',icon:'ki-arrows-circle'},{label:'Average duration',value:this.duration(d.averageDurationMs),hint:'Per test run',icon:'ki-time'},{label:'Latest run',value:d.latestRun?this.statusName(d.latestRun.status):'—',hint:d.latestRun?new Date(d.latestRun.startedAtUtc).toLocaleString():'No run',icon:'ki-verify'},{label:'Browser coverage',value:d.browserCoverage,hint:'Browsers with real results',icon:'ki-screen'},{label:'Artifacts',value:d.latestRun?.artifactCount??0,hint:'On latest run',icon:'ki-folder'}];}
 bar(value:number,d:DashboardOverview){const max=Math.max(1,...d.runTrend.flatMap(x=>[x.passed,x.failed,x.flaky]));return Math.max(value?4:0,Math.round(value/max*150));}
 statusClass(status:number){return status===1?'bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300':status===2?'bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-300':'bg-muted text-muted-foreground';}
}
