import { test, expect } from '../../fixtures/diagnostics';
import { AdminShellPage } from '../../pages/admin-shell.page';
import type { Page } from '@playwright/test';

const run={id:'11111111-1111-1111-1111-111111111111',providerRunId:'2048',status:1,branch:'feature/test-analytics-dashboard',commitSha:'abcdef1234567890',pullRequestNumber:45,trigger:'pull_request',executionMode:0,browserSummary:'chromium',passedCount:12,failedCount:0,skippedCount:1,flakyCount:0,durationMs:142000,startedAtUtc:'2026-08-09T08:00:00Z',artifactCount:3,workflowRunUrl:'https://github.com/example/actions/runs/2048'};
const overview={passRate:100,totalRuns:4,testsExecuted:48,failedTests:0,flakyTests:1,averageDurationMs:138000,latestRun:run,browserCoverage:3,runTrend:[{date:'2026-08-07T00:00:00Z',passed:10,failed:1,flaky:1,averageDurationMs:140000},{date:'2026-08-09T00:00:00Z',passed:12,failed:0,flaky:0,averageDurationMs:142000}],durationTrend:[],browsers:[{browser:'chromium',tests:30,passed:30,failed:0,passRate:100,averageDurationMs:8000,latestStatus:0},{browser:'webkit',tests:8,passed:8,failed:0,passRate:100,averageDurationMs:9000,latestStatus:0}],executionModes:[{mode:0,runs:3,passRate:100,latestRunAtUtc:'2026-08-09T08:00:00Z',artifacts:4},{mode:1,runs:1,passRate:100,latestRunAtUtc:'2026-08-08T08:00:00Z',artifacts:6}],features:[{feature:'projects',tests:25,lastTestedAtUtc:'2026-08-09T08:00:00Z',latestStatus:0,browserCoverage:3,hasVisualEvidence:true,hasRecording:false},{feature:'quality',tests:3,lastTestedAtUtc:'2026-08-09T08:00:00Z',latestStatus:0,browserCoverage:1,hasVisualEvidence:false,hasRecording:false}],flaky:[{testName:'opens project details',feature:'projects',browser:'webkit',executions:4,failures:1,retries:1,flakyRate:25,lastFailedAtUtc:'2026-08-07T08:00:00Z',lastPassedAtUtc:'2026-08-09T08:00:00Z'}],slowest:[{testName:'publishes project',feature:'projects',browser:'chromium',averageDurationMs:18000,latestDurationMs:17000}]};
const details={run,workflowName:'Playwright E2E',workflowRunNumber:2048,completedAtUtc:'2026-08-09T08:02:22Z',featureSummary:'quality, projects',repositoryUrl:'https://github.com/example/repo',pullRequestUrl:'https://github.com/example/repo/pull/45',tests:[{id:'22222222-2222-2222-2222-222222222222',feature:'quality',suite:'Portfolio.Admin quality',testName:'loads summary cards',projectArea:'Admin',browser:'chromium',viewport:'1440x900',status:0,durationMs:3200,retryCount:0,isFlaky:false,errorType:null,errorSummary:null,sourceFile:'tests/playwright/admin/quality/smoke.spec.ts'}],artifacts:[{id:'33333333-3333-3333-3333-333333333333',testCaseResultId:null,artifactType:0,provider:0,providerArtifactId:'playwright-report',name:'Playwright HTML report',mimeType:'text/html',externalUrl:'https://github.com/example/actions/runs/2048',storagePath:'playwright-report/',sizeBytes:null,createdAtUtc:'2026-08-09T08:02:22Z',expiresAtUtc:'2026-08-23T08:02:22Z',availabilityStatus:0,browser:'chromium',feature:'quality'}]};

async function mockDashboard(page: Page, empty=false){
 await page.route(/\/api\/admin\/test-analytics\/overview(?:\?|$)/,route=>route.fulfill({json:empty?{...overview,totalRuns:0,testsExecuted:0,latestRun:null,runTrend:[],browsers:[],executionModes:[],features:[],flaky:[],slowest:[]}:overview}));
 await page.route(/\/api\/admin\/test-analytics\/runs(?:\?|$)/,route=>route.fulfill({json:{items:empty?[]:[run],page:1,pageSize:10,totalCount:empty?0:1,totalPages:empty?0:1}}));
}

test.describe('Portfolio.Admin quality analytics',()=>{
 test('opens Test Analytics, renders health metrics and filters runs',async({page})=>{await mockDashboard(page);const admin=new AdminShellPage(page);await admin.open();await admin.navigate('Quality');await expect(page).toHaveURL(/\/quality\/tests/);await expect(page.getByRole('heading',{name:'Test Analytics',exact:true})).toBeVisible();await expect(page.getByText('100%').first()).toBeVisible();await expect(page.getByRole('heading',{name:'Recent runs'})).toBeVisible();await page.getByLabel('Browser').selectOption('chromium');await page.getByRole('button',{name:'Apply filters'}).click();await expect(page).toHaveURL(/browser=chromium/);});
 test('opens run details and artifact metadata',async({page})=>{await mockDashboard(page);await page.route(/\/api\/admin\/test-analytics\/runs\/11111111-1111-1111-1111-111111111111$/,route=>route.fulfill({json:details}));const admin=new AdminShellPage(page);await admin.open('/quality/tests');await page.getByRole('link',{name:'View run'}).click();await expect(page.getByRole('heading',{name:'Run #2048'})).toBeVisible();await expect(page.getByRole('heading',{name:'Test-case results'})).toBeVisible();await expect(page.getByText('Playwright HTML report')).toBeVisible();await expect(page.getByText(/Available until/)).toBeVisible();});
  test('shows an honest no-history state',async({page})=>{await mockDashboard(page,true);const admin=new AdminShellPage(page);await admin.open('/quality/tests');await expect(page.getByRole('heading',{name:'No test history yet'})).toBeVisible();});
  test('keeps priority metrics and filters usable on mobile',async({page})=>{await page.setViewportSize({width:430,height:900});await mockDashboard(page);const admin=new AdminShellPage(page);await admin.open('/quality/tests');await expect(page.getByRole('heading',{name:'Test Analytics',exact:true})).toBeVisible();await expect(page.getByText('Pass rate')).toBeVisible();await expect(page.getByLabel('Status')).toBeVisible();await expect(page.getByRole('heading',{name:'Recent runs'})).toBeVisible();});
});
