import { HttpErrorResponse } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, DestroyRef, computed, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { finalize, forkJoin } from 'rxjs';
import { AdminConfirmationDialogComponent } from '../../../../shared/components/admin-confirmation-dialog/admin-confirmation-dialog.component';
import { AdminPageHeaderComponent } from '../../../../shared/components/admin-page-header/admin-page-header.component';
import { AdminToastComponent } from '../../../../shared/components/admin-toast/admin-toast.component';
import { InfographicPendingChangesAware } from '../../data-access/pending-infographic-changes.guard';
import { Category, DifficultyLevel, InfographicCodeExample, InfographicDraft, InfographicResource, InfographicStep, MediaFile, Tag, difficultyLabel } from '../../data-access/infographic.models';
import { InfographicsApiService } from '../../data-access/infographics-api.service';

@Component({selector:'app-infographic-editor',imports:[ReactiveFormsModule,RouterLink,AdminPageHeaderComponent,AdminConfirmationDialogComponent,AdminToastComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<app-admin-page-header [title]="id()?'Edit Infographic':'Create Infographic'" description="Create a structured, publish-ready Visual Handbook guide." [breadcrumbs]="[{label:'Infographics',link:'/infographics'},{label:id()?'Edit':'Create'}]"><a adminPageActions routerLink="/infographics" class="kt-btn kt-btn-outline">Back to infographics</a></app-admin-page-header>
@if(loading()){<div class="grid gap-4"><div class="h-14 animate-pulse rounded-xl bg-muted"></div><div class="h-96 animate-pulse rounded-2xl bg-muted"></div></div>}
@else if(loadError()){<div class="rounded-2xl border border-red-300 bg-red-50 p-8 text-center dark:bg-red-950/20"><h2 class="font-semibold text-red-800 dark:text-red-300">Infographic could not be loaded</h2><p class="mt-2 text-sm text-red-700 dark:text-red-400">{{loadError()}}</p><button class="kt-btn kt-btn-outline mt-5" (click)="load()">Retry</button></div>}
@else{
<nav class="mb-6 overflow-x-auto" aria-label="Infographic creation steps"><ol class="flex min-w-max items-center gap-2">@for(step of stepLabels;track step;let index=$index){<li><button type="button" class="flex min-h-11 items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold" [class.bg-primary]="currentStep()===index" [class.text-white]="currentStep()===index" [class.text-primary]="currentStep()>index" (click)="goTo(index)" [attr.aria-current]="currentStep()===index?'step':null"><span class="grid size-7 place-items-center rounded-full border" aria-hidden="true">{{currentStep()>index?'✓':index+1}}</span>{{step}}</button></li>}</ol></nav>
<div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_330px]">
<main class="rounded-[20px] border border-border bg-background p-5 shadow-sm sm:p-7">
@switch(currentStep()){
@case(0){<form [formGroup]="form" class="grid gap-6"><div><h2 class="text-lg font-semibold">Basic Information</h2><p class="mt-1 text-sm text-muted-foreground">Add the essential information used across cards and detail pages.</p></div><div class="grid gap-5 md:grid-cols-2"><label class="grid gap-2 text-sm font-medium">Title *<input class="kt-input" formControlName="title" placeholder="EF Core Performance Checklist">@if(form.controls.title.touched&&form.controls.title.invalid){<span class="text-xs text-red-600">Title is required.</span>}</label><label class="grid gap-2 text-sm font-medium">Slug *<input class="kt-input" formControlName="slug" placeholder="ef-core-performance-checklist">@if(form.controls.slug.touched&&form.controls.slug.invalid){<span class="text-xs text-red-600">Use lowercase letters, numbers, and hyphens.</span>}</label></div><label class="grid gap-2 text-sm font-medium">Short Description *<textarea class="kt-textarea min-h-24" formControlName="shortDescription" maxlength="500"></textarea><span class="text-end text-xs text-muted-foreground">{{form.controls.shortDescription.value.length}} / 500</span></label><label class="grid gap-2 text-sm font-medium">Introduction<textarea class="kt-textarea min-h-36" formControlName="description" placeholder="Explain what the reader will understand and why it matters."></textarea></label><div class="grid gap-5 md:grid-cols-2"><label class="grid gap-2 text-sm font-medium">Category *<select class="kt-select" formControlName="categoryId"><option value="">Select category</option>@for(item of categories();track item.id){<option [value]="item.id">{{item.name}}</option>}</select></label><label class="grid gap-2 text-sm font-medium">Difficulty *<select class="kt-select" formControlName="difficultyLevel"><option [value]="1">Beginner</option><option [value]="2">Intermediate</option><option [value]="3">Advanced</option></select></label></div><fieldset><legend class="text-sm font-medium">Tags</legend><div class="mt-3 flex flex-wrap gap-2">@for(item of tags();track item.id){<label class="flex min-h-10 cursor-pointer items-center gap-2 rounded-full border border-border px-3 text-sm" [class.border-primary]="tagIds().includes(item.id)" [class.bg-primary/10]="tagIds().includes(item.id)"><input type="checkbox" [checked]="tagIds().includes(item.id)" (change)="toggleTag(item.id)">{{item.name}}</label>}</div></fieldset><label class="flex min-h-11 items-center gap-3 rounded-xl border border-border p-4"><input type="checkbox" formControlName="isFeatured"><span><strong class="block text-sm">Featured infographic</strong><span class="text-xs text-muted-foreground">Eligible for the Homepage Visual Handbook preview.</span></span></label></form>}
@case(1){<div class="grid gap-7"><div><h2 class="text-lg font-semibold">Content</h2><p class="mt-1 text-sm text-muted-foreground">Build ordered sections, helpful resources, and focused code examples.</p></div><section><div class="flex items-center justify-between"><h3 class="font-semibold">Content Sections</h3><button type="button" class="kt-btn kt-btn-sm kt-btn-outline" (click)="addStep()"><i class="ki-filled ki-plus"></i>Add Step</button></div><div class="mt-4 grid gap-4">@for(item of steps();track $index;let index=$index){<article class="rounded-2xl border border-border bg-muted/20 p-4"><div class="flex items-center justify-between gap-3"><strong>Step {{index+1}}</strong><div class="flex gap-1"><button class="kt-btn kt-btn-sm kt-btn-outline" type="button" [disabled]="index===0" (click)="moveStep(index,-1)" aria-label="Move step up">↑</button><button class="kt-btn kt-btn-sm kt-btn-outline" type="button" [disabled]="index===steps().length-1" (click)="moveStep(index,1)" aria-label="Move step down">↓</button><button class="kt-btn kt-btn-sm kt-btn-destructive" type="button" (click)="removeStep(index)" aria-label="Remove step"><i class="ki-filled ki-trash"></i></button></div></div><div class="mt-4 grid gap-4"><label class="grid gap-2 text-sm font-medium">Step title *<input class="kt-input" [value]="item.title" (input)="updateStep(index,'title',$any($event.target).value)"></label><label class="grid gap-2 text-sm font-medium">Explanation<textarea class="kt-textarea min-h-28" [value]="item.content||''" (input)="updateStep(index,'content',$any($event.target).value)"></textarea></label></div></article>}@empty{<div class="rounded-2xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">No content sections yet. Add the first step to make this guide publish-ready.</div>}</div></section>
<section class="border-t border-border pt-6"><div class="flex items-center justify-between"><h3 class="font-semibold">Resources</h3><button class="kt-btn kt-btn-sm kt-btn-outline" type="button" (click)="addResource()">Add Resource</button></div><div class="mt-4 grid gap-3">@for(item of resources();track $index;let index=$index){<div class="grid gap-3 rounded-xl border border-border p-4 md:grid-cols-[1fr_1.4fr_150px_auto]"><input class="kt-input" aria-label="Resource title" placeholder="Title" [value]="item.title" (input)="updateResource(index,'title',$any($event.target).value)"><input class="kt-input" aria-label="Resource URL" placeholder="https://..." [value]="item.url" (input)="updateResource(index,'url',$any($event.target).value)"><input class="kt-input" aria-label="Resource type" placeholder="Documentation" [value]="item.resourceType" (input)="updateResource(index,'resourceType',$any($event.target).value)"><button class="kt-btn kt-btn-sm kt-btn-destructive" type="button" (click)="removeResource(index)">Remove</button></div>}</div></section>
<section class="border-t border-border pt-6"><div class="flex items-center justify-between"><h3 class="font-semibold">Code Examples</h3><button class="kt-btn kt-btn-sm kt-btn-outline" type="button" (click)="addCodeExample()">Add Example</button></div><div class="mt-4 grid gap-4">@for(item of codeExamples();track $index;let index=$index){<article class="rounded-xl border border-border p-4"><div class="grid gap-3 md:grid-cols-[1fr_180px_auto]"><input class="kt-input" aria-label="Code example title" placeholder="Title" [value]="item.title" (input)="updateCode(index,'title',$any($event.target).value)"><input class="kt-input" aria-label="Code language" placeholder="csharp" [value]="item.language" (input)="updateCode(index,'language',$any($event.target).value)"><button class="kt-btn kt-btn-sm kt-btn-destructive" type="button" (click)="removeCodeExample(index)">Remove</button></div><textarea class="kt-textarea mt-3 min-h-36 font-mono text-xs" aria-label="Code" [value]="item.code" (input)="updateCode(index,'code',$any($event.target).value)"></textarea></article>}</div></section></div>}
@case(2){<div class="grid gap-6"><div><h2 class="text-lg font-semibold">Media & Files</h2><p class="mt-1 text-sm text-muted-foreground">Reference existing Media Library metadata. Files remain outside SQL Server.</p></div><div class="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900 dark:border-blue-900 dark:bg-blue-950/30 dark:text-blue-200"><strong>Issue #49 boundary:</strong> this slice supports safe existing-media selection and previews. Upload, replacement, and storage-provider administration remain in the Media Library feature.</div><label class="grid gap-2 text-sm font-medium">Cover image<select class="kt-select" [value]="coverMediaId()||''" (change)="coverMediaId.set(valueOrNull($any($event.target).value));markDirty()"><option value="">No cover image</option>@for(item of imageMedia();track item.id){<option [value]="item.id">{{item.originalFileName}}</option>}</select></label><label class="grid gap-2 text-sm font-medium">Main infographic image<select class="kt-select" [value]="infographicMediaId()||''" (change)="infographicMediaId.set(valueOrNull($any($event.target).value));markDirty()"><option value="">No main image</option>@for(item of imageMedia();track item.id){<option [value]="item.id">{{item.originalFileName}}</option>}</select></label><label class="grid gap-2 text-sm font-medium">PDF download<select class="kt-select" [value]="pdfMediaId()||''" (change)="pdfMediaId.set(valueOrNull($any($event.target).value));markDirty()"><option value="">No PDF</option>@for(item of pdfMedia();track item.id){<option [value]="item.id">{{item.originalFileName}}</option>}</select></label>@if(!media().length){<div class="rounded-2xl border border-dashed border-border p-10 text-center"><i class="ki-filled ki-picture text-3xl text-primary"></i><h3 class="mt-3 font-semibold">No reusable media yet</h3><p class="mt-2 text-sm text-muted-foreground">The infographic can be published without optional media. The full upload workflow is deferred to Issue #49.</p></div>}</div>}
@case(3){<div class="grid gap-6"><div><h2 class="text-lg font-semibold">SEO & Settings</h2><p class="mt-1 text-sm text-muted-foreground">Review the metadata derived from the infographic content.</p></div><div class="grid gap-4 rounded-2xl border border-border bg-muted/20 p-5"><div><span class="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Page title</span><p class="mt-1 font-semibold">{{form.controls.title.value||'Infographic title'}} | Sultan Alomran</p></div><div><span class="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Meta description</span><p class="mt-1 text-sm text-muted-foreground">{{form.controls.shortDescription.value||'Add a short description.'}}</p></div><div><span class="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Public URL</span><p class="mt-1 break-all font-mono text-sm">/visual-handbook/{{form.controls.slug.value||'your-slug'}}</p></div></div><p class="text-sm text-muted-foreground">Canonical and Open Graph metadata use these values; no duplicate SEO fields are stored.</p></div>}
@case(4){<div class="grid gap-6"><div><h2 class="text-lg font-semibold">Review & Publish</h2><p class="mt-1 text-sm text-muted-foreground">Review the complete guide and resolve missing publishing requirements.</p></div><div class="grid gap-4 sm:grid-cols-2"><div class="rounded-xl border border-border p-4"><span class="text-xs uppercase text-muted-foreground">Title</span><strong class="mt-1 block">{{form.controls.title.value}}</strong></div><div class="rounded-xl border border-border p-4"><span class="text-xs uppercase text-muted-foreground">Category</span><strong class="mt-1 block">{{selectedCategory()?.name||'Not selected'}}</strong></div><div class="rounded-xl border border-border p-4"><span class="text-xs uppercase text-muted-foreground">Difficulty</span><strong class="mt-1 block">{{difficulty(form.controls.difficultyLevel.value)}}</strong></div><div class="rounded-xl border border-border p-4"><span class="text-xs uppercase text-muted-foreground">Content</span><strong class="mt-1 block">{{steps().length}} steps · {{resources().length}} resources · {{codeExamples().length}} examples</strong></div><div class="rounded-xl border border-border p-4"><span class="text-xs uppercase text-muted-foreground">Media</span><strong class="mt-1 block">{{mediaSummary()}}</strong></div><div class="rounded-xl border border-border p-4"><span class="text-xs uppercase text-muted-foreground">Tags</span><strong class="mt-1 block">{{tagIds().length}} selected</strong></div></div>@if(!form.controls.description.value||!steps().length){<div class="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900 dark:bg-amber-950/30 dark:text-amber-200"><strong>Publishing checklist</strong><ul class="mt-2 list-disc ps-5">@if(!form.controls.description.value){<li>Add an introduction or description.</li>}@if(!steps().length){<li>Add at least one content step.</li>}</ul></div>}@else{<div class="rounded-xl border border-green-300 bg-green-50 p-4 text-sm text-green-900 dark:bg-green-950/30 dark:text-green-200"><strong>Ready to publish.</strong> Required content is complete.</div>}</div>}}
<div class="mt-8 flex flex-wrap items-center justify-between gap-3 border-t border-border pt-5"><button type="button" class="kt-btn kt-btn-outline" [disabled]="currentStep()===0" (click)="previous()">Back</button><div class="flex flex-wrap gap-2"><button type="button" class="kt-btn kt-btn-outline" [disabled]="saving()" (click)="saveDraft()">{{saving()?'Saving…':'Save Draft'}}</button>@if(currentStep()<4){<button type="button" class="kt-btn kt-btn-primary" (click)="next()">Next</button>}@else{<button type="button" class="kt-btn kt-btn-primary" [disabled]="saving()||!publishReady()" (click)="publishDialog.set(true)">Publish Infographic</button>}</div></div>
</main>
<aside class="self-start rounded-[20px] border border-border bg-background p-5 shadow-sm xl:sticky xl:top-6"><p class="text-xs font-bold uppercase tracking-[.16em] text-primary">Live preview</p><div class="mt-4 overflow-hidden rounded-2xl bg-slate-950 p-5 text-white"><span class="text-xs font-semibold text-violet-300">{{selectedCategory()?.name||'Visual Handbook'}}</span><h2 class="mt-3 text-xl font-bold">{{form.controls.title.value||'Your infographic title'}}</h2><p class="mt-3 text-sm leading-6 text-slate-300">{{form.controls.shortDescription.value||'The short description appears here as you type.'}}</p><div class="mt-5 flex flex-wrap gap-1">@for(tag of selectedTags().slice(0,4);track tag.id){<span class="rounded-full bg-white/10 px-2 py-1 text-[11px]">{{tag.name}}</span>}</div></div><ul class="mt-5 grid gap-2 text-sm text-muted-foreground"><li>{{steps().length}} content sections</li><li>{{difficulty(form.controls.difficultyLevel.value)}} difficulty</li><li>{{form.controls.isFeatured.value?'Featured':'Standard'}} placement</li></ul></aside>
</div>}
<app-admin-confirmation-dialog [open]="publishDialog()" title="Publish infographic?" message="The guide will become visible in the public Visual Handbook." confirmLabel="Publish" (dismissed)="publishDialog.set(false)" (confirmed)="publish()"/>
@if(toast()){<div class="fixed bottom-5 end-5 z-[80]"><app-admin-toast title="Infographic saved" [message]="toast()!" (dismiss)="toast.set(null)"/></div>}
`})
export default class InfographicEditorComponent implements InfographicPendingChangesAware{
  private readonly api=inject(InfographicsApiService);private readonly fb=inject(FormBuilder);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly destroyRef=inject(DestroyRef);
  readonly id=signal<string|null>(this.route.snapshot.paramMap.get('id'));readonly currentStep=signal(0);readonly loading=signal(true);readonly loadError=signal<string|null>(null);readonly saving=signal(false);readonly dirty=signal(false);readonly publishDialog=signal(false);readonly toast=signal<string|null>(null);readonly categories=signal<Category[]>([]);readonly tags=signal<Tag[]>([]);readonly media=signal<MediaFile[]>([]);readonly tagIds=signal<string[]>([]);readonly steps=signal<InfographicStep[]>([]);readonly resources=signal<InfographicResource[]>([]);readonly codeExamples=signal<InfographicCodeExample[]>([]);readonly coverMediaId=signal<string|null>(null);readonly infographicMediaId=signal<string|null>(null);readonly pdfMediaId=signal<string|null>(null);readonly stepLabels=['Basic Info','Content','Media & Files','SEO & Settings','Review & Publish'];readonly difficulty=difficultyLabel;
  readonly form=this.fb.nonNullable.group({title:['',[Validators.required,Validators.maxLength(250)]],slug:['',[Validators.required,Validators.pattern(/^[a-z0-9]+(?:-[a-z0-9]+)*$/)]],shortDescription:['',[Validators.required,Validators.maxLength(500)]],description:[''],categoryId:['',Validators.required],difficultyLevel:[2 as DifficultyLevel,Validators.required],isFeatured:[false]});
  readonly selectedCategory=computed(()=>this.categories().find(x=>x.id===this.form.controls.categoryId.value));readonly selectedTags=computed(()=>this.tags().filter(x=>this.tagIds().includes(x.id)));readonly imageMedia=computed(()=>this.media().filter(x=>x.mimeType.startsWith('image/')));readonly pdfMedia=computed(()=>this.media().filter(x=>x.mimeType==='application/pdf'));readonly publishReady=computed(()=>this.form.valid&&!!this.form.controls.description.value.trim()&&this.steps().length>0);
  constructor(){this.form.valueChanges.pipe(takeUntilDestroyed()).subscribe(()=>{this.dirty.set(true);const title=this.form.controls.title.value;if(!this.form.controls.slug.dirty)this.form.controls.slug.setValue(this.slugify(title),{emitEvent:false})});this.load()}
  load(){this.loading.set(true);this.loadError.set(null);forkJoin({categories:this.api.categories(),tags:this.api.tags(),media:this.api.media()}).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:lookups=>{this.categories.set(lookups.categories);this.tags.set(lookups.tags);this.media.set(lookups.media);if(this.id())this.loadItem();else{this.loading.set(false);this.dirty.set(false)}},error:e=>{this.loading.set(false);this.loadError.set(this.message(e))}})}
  private loadItem(){this.api.get(this.id()!).pipe(finalize(()=>this.loading.set(false)),takeUntilDestroyed(this.destroyRef)).subscribe({next:item=>{this.form.patchValue({title:item.title,slug:item.slug,shortDescription:item.shortDescription,description:item.description||'',categoryId:item.categoryId,difficultyLevel:item.difficultyLevel,isFeatured:item.isFeatured},{emitEvent:false});this.tagIds.set(item.tags.map(x=>x.id));this.steps.set(item.steps);this.resources.set(item.resources);this.codeExamples.set(item.codeExamples);this.coverMediaId.set(item.coverMediaFileId||null);this.infographicMediaId.set(item.infographicMediaFileId||null);this.pdfMediaId.set(item.pdfMediaFileId||null);this.dirty.set(false)},error:e=>this.loadError.set(this.message(e))})}
  toggleTag(id:string){this.tagIds.update(values=>values.includes(id)?values.filter(x=>x!==id):[...values,id]);this.markDirty()}
  addStep(){this.steps.update(values=>[...values,{stepNumber:values.length+1,title:'',content:'',mediaFileId:null,displayOrder:values.length}]);this.markDirty()}
  updateStep(index:number,key:'title'|'content',value:string){this.steps.update(items=>items.map((x,i)=>i===index?{...x,[key]:value}:x));this.markDirty()}
  removeStep(index:number){this.steps.update(items=>items.filter((_,i)=>i!==index).map((x,i)=>({...x,stepNumber:i+1,displayOrder:i})));this.markDirty()}
  moveStep(index:number,direction:number){const target=index+direction;if(target<0||target>=this.steps().length)return;this.steps.update(items=>{const next=[...items];[next[index],next[target]]=[next[target],next[index]];return next.map((x,i)=>({...x,stepNumber:i+1,displayOrder:i}))});this.markDirty()}
  addResource(){this.resources.update(x=>[...x,{title:'',url:'',resourceType:'Documentation',displayOrder:x.length}]);this.markDirty()}
  updateResource(index:number,key:'title'|'url'|'resourceType',value:string){this.resources.update(items=>items.map((x,i)=>i===index?{...x,[key]:value}:x));this.markDirty()}
  removeResource(index:number){this.resources.update(items=>items.filter((_,i)=>i!==index).map((x,i)=>({...x,displayOrder:i})));this.markDirty()}
  addCodeExample(){this.codeExamples.update(x=>[...x,{title:'',language:'csharp',code:'',displayOrder:x.length}]);this.markDirty()}
  updateCode(index:number,key:'title'|'language'|'code',value:string){this.codeExamples.update(items=>items.map((x,i)=>i===index?{...x,[key]:value}:x));this.markDirty()}
  removeCodeExample(index:number){this.codeExamples.update(items=>items.filter((_,i)=>i!==index).map((x,i)=>({...x,displayOrder:i})));this.markDirty()}
  goTo(step:number){if(step>0&&this.form.invalid){this.form.markAllAsTouched();this.currentStep.set(0);return}this.currentStep.set(step)}previous(){this.currentStep.update(x=>Math.max(0,x-1))}next(){this.goTo(Math.min(4,this.currentStep()+1))}
  saveDraft(){this.persist(false)}publish(){this.publishDialog.set(false);this.persist(true)}
  private persist(publish:boolean){if(this.form.invalid){this.form.markAllAsTouched();this.currentStep.set(0);return}this.saving.set(true);const request=this.draft();const save$=this.id()?this.api.update(this.id()!,request):this.api.create(request);save$.pipe(finalize(()=>this.saving.set(false)),takeUntilDestroyed(this.destroyRef)).subscribe({next:saved=>{this.id.set(saved.id);const action$=publish?this.api.publish(saved.id):this.api.saveDraft(saved.id);action$.pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:result=>{this.dirty.set(false);this.toast.set(publish?'Infographic published successfully.':'Draft saved successfully.');if(!this.route.snapshot.paramMap.get('id'))this.router.navigate(['/infographics',result.id,'edit'],{replaceUrl:true})},error:e=>this.loadError.set(this.message(e))})},error:e=>{this.loadError.set(this.message(e));this.currentStep.set(0)}})}
  draft():InfographicDraft{const value=this.form.getRawValue();return{...value,difficultyLevel:value.difficultyLevel as DifficultyLevel,description:value.description||undefined,tagIds:this.tagIds(),steps:this.steps(),resources:this.resources(),codeExamples:this.codeExamples(),coverMediaFileId:this.coverMediaId(),infographicMediaFileId:this.infographicMediaId(),pdfMediaFileId:this.pdfMediaId()}}
  mediaSummary(){return[this.coverMediaId()&&'cover',this.infographicMediaId()&&'main image',this.pdfMediaId()&&'PDF'].filter(Boolean).join(', ')||'No optional media'}valueOrNull(value:string){return value||null}markDirty(){this.dirty.set(true)}hasUnsavedChanges(){return this.dirty()}
  private slugify(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
  private message(response:HttpErrorResponse){const body=response.error as {errors?:Record<string,string[]>;detail?:string}|null;return body?.errors?Object.values(body.errors).flat().join(' '):body?.detail||'The request could not be completed.'}
}
