import { ChangeDetectionStrategy, Component, input, output, signal } from '@angular/core';
import { ProjectLink } from '../../data-access/project.models';

@Component({ selector: 'app-links-step', changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<section class="grid gap-5"><div><h2 class="text-xl font-semibold">Project Links</h2><p class="mt-1 text-sm text-muted-foreground">Add ordered, public HTTP or HTTPS destinations.</p></div>
    <div class="grid gap-3 rounded-2xl border border-border p-4 sm:grid-cols-3"><input class="kt-input" placeholder="Label" [value]="title()" (input)="title.set($any($event.target).value)"><input class="kt-input" placeholder="https://..." [value]="url()" (input)="url.set($any($event.target).value)"><select class="kt-select" [value]="type()" (change)="type.set($any($event.target).value)"><option value="live">Live project</option><option value="source">Source code</option><option value="documentation">Documentation</option></select><button type="button" class="kt-btn kt-btn-primary sm:col-span-3 sm:justify-self-start" [disabled]="!title() || !validUrl()" (click)="add()"><i class="ki-filled ki-plus"></i>Add link</button>@if (url() && !validUrl()) {<p class="text-sm text-red-600 sm:col-span-3">Enter a valid HTTP or HTTPS URL.</p>}</div>
    @if (!links().length) {<div class="rounded-xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">No project links added.</div>}
    @else {<ol class="grid gap-3">@for (link of links(); track link.url; let index=$index) {<li class="flex flex-wrap items-center gap-3 rounded-xl border border-border p-4"><i class="ki-filled ki-exit-right-corner text-primary"></i><div class="min-w-0 grow"><p class="text-sm font-semibold">{{ link.title }}</p><p class="truncate text-xs text-muted-foreground">{{ link.url }}</p></div><span class="rounded-full bg-muted px-2 py-1 text-xs">{{ link.linkType }}</span><button class="kt-btn kt-btn-sm kt-btn-outline" type="button" [disabled]="index===0" (click)="move(index,-1)">↑</button><button class="kt-btn kt-btn-sm kt-btn-outline" type="button" [disabled]="index===links().length-1" (click)="move(index,1)">↓</button><button class="kt-btn kt-btn-sm kt-btn-destructive" type="button" (click)="remove(index)"><i class="ki-filled ki-trash"></i></button></li>}</ol>}</section>` })
export default class LinksStepComponent {
  readonly links=input<readonly ProjectLink[]>([]); readonly linksChange=output<ProjectLink[]>(); readonly title=signal(''); readonly url=signal(''); readonly type=signal('live');
  validUrl(){try{const value=new URL(this.url());return ['http:','https:'].includes(value.protocol)}catch{return false}}
  add(){this.linksChange.emit([...this.links(),{title:this.title().trim(),url:this.url().trim(),linkType:this.type(),displayOrder:this.links().length}]);this.title.set('');this.url.set('')}
  remove(index:number){this.linksChange.emit(this.links().filter((_,i)=>i!==index).map((x,i)=>({...x,displayOrder:i})))}
  move(index:number,delta:number){const copy=[...this.links()];[copy[index],copy[index+delta]]=[copy[index+delta],copy[index]];this.linksChange.emit(copy.map((x,i)=>({...x,displayOrder:i})))}
}
