import { ChangeDetectionStrategy, Component, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { RouterLink } from '@angular/router';
import { finalize, forkJoin } from 'rxjs';
import { AdminConfirmationDialogComponent } from '../../../../shared/components/admin-confirmation-dialog/admin-confirmation-dialog.component';
import { AdminEmptyStateComponent } from '../../../../shared/components/admin-empty-state/admin-empty-state.component';
import { AdminLoadingSkeletonComponent } from '../../../../shared/components/admin-loading-skeleton/admin-loading-skeleton.component';
import { AdminPageHeaderComponent } from '../../../../shared/components/admin-page-header/admin-page-header.component';
import { AdminPaginationComponent } from '../../../../shared/components/admin-pagination/admin-pagination.component';
import { AdminStatus, AdminStatusBadgeComponent } from '../../../../shared/components/admin-status-badge/admin-status-badge.component';
import { AdminInfographicListItem, Category, ContentStatus, Tag, difficultyLabel, statusLabel } from '../../data-access/infographic.models';
import { InfographicsApiService } from '../../data-access/infographics-api.service';

@Component({selector:'app-infographic-list',imports:[RouterLink,AdminPageHeaderComponent,AdminEmptyStateComponent,AdminLoadingSkeletonComponent,AdminPaginationComponent,AdminStatusBadgeComponent,AdminConfirmationDialogComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<app-admin-page-header title="Infographics" description="Manage and organize all infographics in the Visual Handbook." [breadcrumbs]="[{label:'Infographics'}]">
  <a adminPageActions routerLink="/infographics/create" class="kt-btn kt-btn-primary"><i class="ki-filled ki-plus"></i>Create Infographic</a>
</app-admin-page-header>
<section class="overflow-hidden rounded-[20px] border border-border bg-background shadow-sm">
  <div class="grid gap-3 border-b border-border p-4 md:grid-cols-2 xl:grid-cols-[minmax(240px,1fr)_180px_180px_160px_150px_auto]">
    <label class="relative"><span class="sr-only">Search infographics</span><i class="ki-filled ki-magnifier absolute start-3 top-3 text-muted-foreground"></i><input class="kt-input ps-10" placeholder="Search title or summary" [value]="search()" (input)="search.set($any($event.target).value)" (keyup.enter)="reload(1)"></label>
    <select class="kt-select" aria-label="Category filter" [value]="category()" (change)="category.set($any($event.target).value);reload(1)"><option value="">All categories</option>@for(item of categories();track item.id){<option [value]="item.slug">{{item.name}}</option>}</select>
    <select class="kt-select" aria-label="Tag filter" [value]="tag()" (change)="tag.set($any($event.target).value);reload(1)"><option value="">All tags</option>@for(item of tags();track item.id){<option [value]="item.slug">{{item.name}}</option>}</select>
    <select class="kt-select" aria-label="Status filter" [value]="status()" (change)="status.set($any($event.target).value);reload(1)"><option value="">All statuses</option><option value="0">Draft</option><option value="1">Published</option><option value="2">Archived</option></select>
    <select class="kt-select" aria-label="Sort infographics" [value]="sort()" (change)="sort.set($any($event.target).value);reload(1)"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="title">Title</option></select>
    <button class="kt-btn kt-btn-outline" type="button" (click)="reload(1)">Apply</button>
  </div>
  @if(loading()){<div class="p-5"><app-admin-loading-skeleton [rows]="6"/></div>}
  @else if(error()){<div class="p-10 text-center"><i class="ki-filled ki-information-2 text-3xl text-red-500"></i><h2 class="mt-3 font-semibold">Infographics could not be loaded</h2><p class="mt-2 text-sm text-muted-foreground">{{error()}}</p><button class="kt-btn kt-btn-outline mt-5" (click)="reload()">Retry</button></div>}
  @else if(!items().length){<div class="p-6"><app-admin-empty-state title="No infographics yet" description="Create the first Visual Handbook guide or adjust the current filters." icon="ki-book-open"><a emptyStateAction routerLink="/infographics/create" class="kt-btn kt-btn-primary">Create Infographic</a></app-admin-empty-state></div>}
  @else{<div class="overflow-x-auto"><table class="w-full min-w-[920px] text-start text-sm"><thead class="border-b border-border bg-muted/40 text-xs uppercase tracking-wide text-muted-foreground"><tr><th class="p-4 text-start">Infographic</th><th class="p-4 text-start">Category</th><th class="p-4 text-start">Difficulty</th><th class="p-4 text-start">Status</th><th class="p-4 text-start">Updated</th><th class="p-4 text-end">Actions</th></tr></thead><tbody>
  @for(item of items();track item.id){<tr class="border-b border-border last:border-0 hover:bg-muted/30"><td class="p-4"><div class="flex items-center gap-3"><div class="grid size-12 shrink-0 place-items-center overflow-hidden rounded-xl bg-gradient-to-br from-primary/20 to-indigo-500/20 text-primary">@if(item.coverUrl){<img [src]="item.coverUrl" [alt]="item.title" class="size-full object-cover">}@else{<i class="ki-filled ki-book-open text-xl"></i>}</div><div class="min-w-0"><div class="flex items-center gap-2"><a [routerLink]="['/infographics',item.id]" class="truncate font-semibold hover:text-primary">{{item.title}}</a>@if(item.isFeatured){<i class="ki-filled ki-star text-amber-500" aria-label="Featured"></i>}</div><p class="max-w-md truncate text-xs text-muted-foreground">/{{item.slug}}</p><div class="mt-1 flex gap-1">@for(label of item.tags.slice(0,3);track label.id){<span class="rounded-full bg-muted px-2 py-0.5 text-[11px]">{{label.name}}</span>}</div></div></div></td><td class="p-4 font-medium">{{item.category.name}}</td><td class="p-4 text-muted-foreground">{{difficulty(item.difficultyLevel)}}</td><td class="p-4"><app-admin-status-badge [status]="badge(item.status)">{{statusName(item.status)}}</app-admin-status-badge></td><td class="p-4 text-muted-foreground">{{(item.updatedAt||item.createdAt).slice(0,10)}}</td><td class="p-4"><div class="flex justify-end gap-2"><a class="kt-btn kt-btn-sm kt-btn-outline" [routerLink]="['/infographics',item.id]" aria-label="View infographic"><i class="ki-filled ki-eye"></i></a><a class="kt-btn kt-btn-sm kt-btn-outline" [routerLink]="['/infographics',item.id,'edit']">Edit</a>@if(item.status===1){<button class="kt-btn kt-btn-sm kt-btn-outline" type="button" (click)="archiveTarget.set(item)">Archive</button>}<button class="kt-btn kt-btn-sm kt-btn-destructive" type="button" (click)="deleteTarget.set(item)" aria-label="Delete infographic"><i class="ki-filled ki-trash"></i></button></div></td></tr>}
  </tbody></table></div><div class="border-t border-border p-4"><app-admin-pagination [page]="page()" [totalItems]="total()" [pageSize]="10" (pageChange)="reload($event)"/></div>}
</section>
<app-admin-confirmation-dialog [open]="!!archiveTarget()" title="Archive infographic?" message="The infographic will be removed from public visibility but remain available to administrators." confirmLabel="Archive" (dismissed)="archiveTarget.set(null)" (confirmed)="archiveConfirmed()"/>
<app-admin-confirmation-dialog [open]="!!deleteTarget()" title="Delete infographic?" message="The infographic will be soft-deleted and removed from the Visual Handbook." confirmLabel="Delete" (dismissed)="deleteTarget.set(null)" (confirmed)="deleteConfirmed()"/>
`})
export default class InfographicListComponent{
  private readonly api=inject(InfographicsApiService);private readonly destroyRef=inject(DestroyRef);
  readonly items=signal<AdminInfographicListItem[]>([]);readonly categories=signal<Category[]>([]);readonly tags=signal<Tag[]>([]);readonly loading=signal(true);readonly error=signal<string|null>(null);readonly search=signal('');readonly category=signal('');readonly tag=signal('');readonly status=signal('');readonly sort=signal('newest');readonly page=signal(1);readonly total=signal(0);readonly archiveTarget=signal<AdminInfographicListItem|null>(null);readonly deleteTarget=signal<AdminInfographicListItem|null>(null);readonly statusName=statusLabel;readonly difficulty=difficultyLabel;
  constructor(){forkJoin({categories:this.api.categories(),tags:this.api.tags()}).pipe(takeUntilDestroyed()).subscribe({next:x=>{this.categories.set(x.categories);this.tags.set(x.tags)}});this.reload()}
  reload(page=this.page()){this.page.set(page);this.loading.set(true);this.error.set(null);this.api.list({search:this.search(),category:this.category(),tag:this.tag(),status:this.status()===''?undefined:Number(this.status()) as ContentStatus,sort:this.sort(),page,pageSize:10}).pipe(finalize(()=>this.loading.set(false)),takeUntilDestroyed(this.destroyRef)).subscribe({next:r=>{this.items.set(r.items);this.total.set(r.totalCount)},error:e=>this.error.set(e?.error?.detail||'Check that the API and local database are running.')})}
  badge(value:ContentStatus):AdminStatus{return value===0?'draft':value===1?'published':'archived'}
  archiveConfirmed(){const item=this.archiveTarget();this.archiveTarget.set(null);if(!item)return;this.api.archive(item.id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:()=>this.reload(),error:()=>this.error.set('The infographic could not be archived.')})}
  deleteConfirmed(){const item=this.deleteTarget();this.deleteTarget.set(null);if(!item)return;this.api.delete(item.id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:()=>this.reload(),error:()=>this.error.set('The infographic could not be deleted.')})}
}
