import { ChangeDetectionStrategy, Component, input, output, signal } from '@angular/core';
import { ProjectImage } from '../../data-access/project.models';

@Component({ selector: 'app-media-gallery-step', changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<section class="grid gap-5"><div><h2 class="text-xl font-semibold">Media and Gallery</h2><p class="mt-1 text-sm text-muted-foreground">Attach existing Media Library records. Binary upload storage is intentionally deferred.</p></div>
    <div class="rounded-2xl border border-dashed border-primary/40 bg-primary/5 p-6"><div class="grid gap-4 sm:grid-cols-2"><label class="grid gap-2 text-sm font-medium">Media file ID<input class="kt-input" [value]="mediaId()" (input)="mediaId.set($any($event.target).value)" placeholder="Existing media GUID"></label><label class="grid gap-2 text-sm font-medium">Alternative text<input class="kt-input" [value]="altText()" (input)="altText.set($any($event.target).value)"></label></div><button type="button" class="kt-btn kt-btn-primary mt-4" [disabled]="!mediaId() || !altText()" (click)="add()"><i class="ki-filled ki-plus"></i>Add image</button></div>
    @if (!images().length) {<div class="rounded-xl border border-dashed border-border p-8 text-center"><i class="ki-filled ki-picture text-3xl text-muted-foreground"></i><p class="mt-3 text-sm text-muted-foreground">No gallery images selected.</p></div>}
    @else {<ol class="grid gap-3">@for (image of images(); track image.mediaFileId; let index = $index) {<li class="flex items-center gap-3 rounded-xl border border-border p-4"><span class="grid size-9 place-items-center rounded-lg bg-muted text-sm font-semibold">{{ index + 1 }}</span><div class="min-w-0 grow"><p class="truncate text-sm font-medium">{{ image.altText }}</p><p class="truncate text-xs text-muted-foreground">{{ image.mediaFileId }}</p></div><button type="button" class="kt-btn kt-btn-sm kt-btn-outline" [disabled]="index === 0" (click)="move(index,-1)" aria-label="Move image up">↑</button><button type="button" class="kt-btn kt-btn-sm kt-btn-outline" [disabled]="index === images().length-1" (click)="move(index,1)" aria-label="Move image down">↓</button><button type="button" class="kt-btn kt-btn-sm kt-btn-destructive" (click)="remove(index)" aria-label="Remove image"><i class="ki-filled ki-trash"></i></button></li>}</ol>}</section>` })
export default class MediaGalleryStepComponent {
  readonly images = input<readonly ProjectImage[]>([]); readonly imagesChange = output<ProjectImage[]>(); readonly mediaId = signal(''); readonly altText = signal('');
  add() { this.imagesChange.emit([...this.images(), { mediaFileId: this.mediaId().trim(), altText: this.altText().trim(), displayOrder: this.images().length }]); this.mediaId.set(''); this.altText.set(''); }
  remove(index: number) { if (window.confirm('Remove this image from the project gallery?')) this.imagesChange.emit(this.images().filter((_, i) => i !== index).map((x, i) => ({...x, displayOrder:i}))); }
  move(index:number, delta:number) { const copy=[...this.images()]; [copy[index],copy[index+delta]]=[copy[index+delta],copy[index]]; this.imagesChange.emit(copy.map((x,i)=>({...x,displayOrder:i}))); }
}
