import { ChangeDetectionStrategy, Component, DestroyRef, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { finalize } from 'rxjs';
import { HttpErrorResponse } from '@angular/common/http';
import { AdminPageHeaderComponent } from '../../../../shared/components/admin-page-header/admin-page-header.component';
import { AdminConfirmationDialogComponent } from '../../../../shared/components/admin-confirmation-dialog/admin-confirmation-dialog.component';
import { AdminToastComponent } from '../../../../shared/components/admin-toast/admin-toast.component';
import BasicInfoStepComponent from '../../components/basic-info-step/basic-info-step.component';
import TechnologiesStepComponent from '../../components/technologies-step/technologies-step.component';
import MediaGalleryStepComponent from '../../components/media-gallery-step/media-gallery-step.component';
import LinksStepComponent from '../../components/links-step/links-step.component';
import ReviewPublishStepComponent from '../../components/review-publish-step/review-publish-step.component';
import { PendingChangesAware } from '../../data-access/pending-changes.guard';
import { ProjectDraft, ProjectImage, ProjectLink, Technology } from '../../data-access/project.models';
import { ProjectsApiService } from '../../data-access/projects-api.service';

@Component({ selector:'app-project-editor', imports:[ReactiveFormsModule,RouterLink,AdminPageHeaderComponent,AdminConfirmationDialogComponent,AdminToastComponent,BasicInfoStepComponent,TechnologiesStepComponent,MediaGalleryStepComponent,LinksStepComponent,ReviewPublishStepComponent], changeDetection:ChangeDetectionStrategy.OnPush,
  template:`<app-admin-page-header [title]="id() ? 'Edit Project' : 'Create Project'" description="Build a complete, publish-ready project case study." [breadcrumbs]="[{label:'Projects',link:'/projects'},{label:id()?'Edit':'Create'}]"><a adminPageActions routerLink="/projects" class="kt-btn kt-btn-outline">Back to projects</a></app-admin-page-header>
  @if (loading()) {<div class="grid gap-4"><div class="h-14 animate-pulse rounded-xl bg-muted"></div><div class="h-96 animate-pulse rounded-2xl bg-muted"></div></div>}
  @else if (loadError()) {<div class="rounded-2xl border border-red-300 bg-red-50 p-8 text-center"><h2 class="font-semibold text-red-800">Project could not be loaded</h2><p class="mt-2 text-sm text-red-700">{{ loadError() }}</p><button class="kt-btn kt-btn-outline mt-5" (click)="load()">Retry</button></div>}
  @else {<div class="mb-6 overflow-x-auto"><ol class="flex min-w-max items-center gap-2" aria-label="Project creation steps">@for (step of steps; track step; let index=$index) {<li><button type="button" class="flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold" [class.bg-primary]="currentStep()===index" [class.text-white]="currentStep()===index" [class.text-primary]="currentStep()>index" (click)="goTo(index)" [attr.aria-current]="currentStep()===index?'step':null"><span class="grid size-7 place-items-center rounded-full border" aria-hidden="true">{{ currentStep()>index?'✓':index+1 }}</span>{{ step }}</button></li>}</ol></div>
  <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><main class="rounded-[20px] border border-border bg-background p-5 shadow-sm sm:p-7">
    @switch (currentStep()) {@case (0) {<app-basic-info-step [form]="form"/>}@case (1) {<app-technologies-step [technologies]="technologies()" [selected]="technologyIds()" [loading]="technologiesLoading()" (selectedChange)="setTechnologies($event)"/>}@case (2) {<app-media-gallery-step [images]="images()" (imagesChange)="setImages($event)"/>}@case (3) {<app-links-step [links]="links()" (linksChange)="setLinks($event)"/>}@case (4) {<app-review-publish-step [draft]="draft()" [selectedTechnologies]="selectedTechnologies()" [ready]="form.valid"/>}}
    <div class="mt-8 flex flex-wrap items-center justify-between gap-3 border-t border-border pt-5"><button type="button" class="kt-btn kt-btn-outline" [disabled]="currentStep()===0" (click)="previous()">Previous</button><div class="flex flex-wrap gap-2"><button type="button" class="kt-btn kt-btn-outline" [disabled]="saving()" (click)="saveDraft()">{{ saving()?'Saving…':'Save Draft' }}</button>@if(currentStep()<4){<button type="button" class="kt-btn kt-btn-primary" (click)="next()">Continue</button>}@else{<button type="button" class="kt-btn kt-btn-primary" [disabled]="!form.valid || saving()" (click)="publishDialog.set(true)">Publish Project</button>}</div></div>
  </main><aside class="hidden self-start rounded-[20px] border border-border bg-background p-5 shadow-sm xl:sticky xl:top-24 xl:block"><p class="text-xs font-semibold uppercase tracking-widest text-primary">Live preview</p><div class="mt-4 aspect-video overflow-hidden rounded-xl bg-gradient-to-br from-violet-600 to-indigo-900">@if(previewImage()){<img [src]="previewImage()" class="size-full object-cover" alt="">}@else{<div class="grid size-full place-items-center text-white/70"><i class="ki-filled ki-picture text-4xl"></i></div>}</div><h2 class="mt-5 text-xl font-bold">{{ form.value.title || 'Project title' }}</h2><p class="mt-2 text-sm leading-6 text-muted-foreground">{{ form.value.shortDescription || 'Your project summary appears here as you write.' }}</p><div class="mt-4 flex flex-wrap gap-2">@for(technology of selectedTechnologies();track technology.id){<span class="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-semibold text-primary">{{technology.name}}</span>}</div></aside></div>}
  @if(toast()){<div class="fixed bottom-5 end-5 z-[80]"><app-admin-toast title="Project saved" [message]="toast()!" (dismiss)="toast.set(null)"/></div>}
  <app-admin-confirmation-dialog [open]="publishDialog()" title="Publish this project?" message="The project will become visible through the public Projects API immediately." confirmLabel="Publish Project" (dismissed)="publishDialog.set(false)" (confirmed)="publish()"/>`,
})
export default class ProjectEditorComponent implements PendingChangesAware {
  private readonly fb=inject(FormBuilder); private readonly api=inject(ProjectsApiService); private readonly route=inject(ActivatedRoute); private readonly router=inject(Router); private readonly destroyRef=inject(DestroyRef);
  readonly id=signal<string|null>(this.route.snapshot.paramMap.get('id')); readonly currentStep=signal(0); readonly loading=signal(false); readonly saving=signal(false); readonly loadError=signal<string|null>(null); readonly toast=signal<string|null>(null); readonly publishDialog=signal(false); readonly dirty=signal(false); readonly technologies=signal<Technology[]>([]); readonly technologiesLoading=signal(true); readonly technologyIds=signal<string[]>([]); readonly images=signal<ProjectImage[]>([]); readonly links=signal<ProjectLink[]>([]); readonly previewImage=signal<string|null>(null);
  readonly steps=['Basic Information','Technologies','Media & Gallery','Links','Review & Publish'];
  readonly form=this.fb.nonNullable.group({title:['',[Validators.required,Validators.maxLength(250)]],slug:['',[Validators.required,Validators.maxLength(200),Validators.pattern(/^[a-z0-9]+(?:-[a-z0-9]+)*$/)]],shortDescription:['',[Validators.required,Validators.maxLength(500)]],description:[''],businessProblem:[''],solution:[''],architecture:[''],keyFeatures:[''],challenges:[''],impact:[''],lessonsLearned:[''],liveUrl:['',Validators.pattern(/^$|https?:\/\/.+/i)],isFeatured:[false]});
  readonly selectedTechnologies=computed(()=>this.technologies().filter(x=>this.technologyIds().includes(x.id)));
  readonly draft=computed<ProjectDraft>(()=>({...this.form.getRawValue(),thumbnailMediaFileId:null,technologies:this.technologyIds().map(technologyId=>({technologyId})),images:this.images(),links:this.links()}));
  constructor(){let slugManuallyChanged=false;this.form.controls.slug.valueChanges.pipe(takeUntilDestroyed()).subscribe(()=>{if(this.form.controls.slug.dirty)slugManuallyChanged=true;this.dirty.set(true)});this.form.controls.title.valueChanges.pipe(takeUntilDestroyed()).subscribe(title=>{this.dirty.set(true);if(!slugManuallyChanged)this.form.controls.slug.setValue(this.slugify(title),{emitEvent:false})});this.form.valueChanges.pipe(takeUntilDestroyed()).subscribe(()=>this.dirty.set(true));this.load();}
  load(){this.api.technologies().pipe(takeUntilDestroyed(this.destroyRef),finalize(()=>this.technologiesLoading.set(false))).subscribe({next:x=>this.technologies.set(x),error:()=>this.technologies.set([])});if(!this.id())return;this.loading.set(true);this.loadError.set(null);this.api.get(this.id()!).pipe(finalize(()=>this.loading.set(false)),takeUntilDestroyed(this.destroyRef)).subscribe({next:p=>{this.form.patchValue(p,{emitEvent:false});this.technologyIds.set(p.technologies.map(x=>x.id));this.images.set(p.images);this.links.set(p.links);this.previewImage.set(p.thumbnailUrl??null);this.dirty.set(false)},error:e=>this.loadError.set(this.message(e))});}
  hasUnsavedChanges(){return this.dirty()}
  setTechnologies(ids:string[]){this.technologyIds.set(ids);this.dirty.set(true)} setImages(items:ProjectImage[]){this.images.set(items);this.dirty.set(true)} setLinks(items:ProjectLink[]){this.links.set(items);this.dirty.set(true)}
  goTo(step:number){if(step>0&&this.form.invalid){this.form.markAllAsTouched();return}this.currentStep.set(step)} previous(){this.currentStep.update(step=>Math.max(0,step-1))} next(){this.goTo(this.currentStep()+1)}
  saveDraft(){this.persist(false)} publish(){this.publishDialog.set(false);this.persist(true)}
  private persist(publish:boolean){if(this.form.invalid){this.form.markAllAsTouched();this.currentStep.set(0);return}this.saving.set(true);const save$=this.id()?this.api.update(this.id()!,this.draft()):this.api.create(this.draft());save$.pipe(finalize(()=>this.saving.set(false)),takeUntilDestroyed(this.destroyRef)).subscribe({next:saved=>{this.id.set(saved.id);const action$=publish?this.api.publish(saved.id):this.api.saveDraft(saved.id);action$.pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:result=>{this.dirty.set(false);this.toast.set(publish?'Published successfully.':'Draft saved successfully.');if(!this.route.snapshot.paramMap.get('id'))this.router.navigate(['/projects',result.id,'edit'],{replaceUrl:true})},error:e=>this.loadError.set(this.message(e))})},error:e=>{this.loadError.set(this.message(e));this.currentStep.set(0)}})}
  private slugify(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
  private message(response:HttpErrorResponse){const body=response.error as {errors?:Record<string,string[]>;detail?:string}|null;return body?.errors?Object.values(body.errors).flat().join(' '):body?.detail||'The request could not be completed.'}
}
