import { ChangeDetectionStrategy, Component, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ActivatedRoute, Router } from '@angular/router';
import { finalize } from 'rxjs';
import ProjectCardComponent from '../../components/project-card/project-card.component';
import { ProjectListItem, Technology } from '../../data-access/project.models';
import { ProjectsApiService } from '../../data-access/projects-api.service';
@Component({selector:'app-projects-list',imports:[ProjectCardComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`<section class="border-b border-border bg-white"><div class="mx-auto max-w-6xl px-5 py-14 sm:py-20"><span class="text-sm font-bold uppercase tracking-[.2em] text-primary">Selected work</span><h1 class="mt-3 max-w-3xl text-4xl font-black tracking-tight sm:text-6xl">Projects built around real engineering decisions.</h1><p class="mt-5 max-w-2xl text-base leading-7 text-muted sm:text-lg">Explore architecture, implementation choices, challenges, and measurable outcomes.</p></div></section><section class="mx-auto max-w-6xl px-5 py-10"><div class="grid gap-3 rounded-2xl border border-border bg-white p-4 shadow-sm md:grid-cols-[1fr_220px_180px_auto]"><label><span class="sr-only">Search projects</span><input class="w-full rounded-xl border border-border px-4 py-3" placeholder="Search projects" [value]="search()" (input)="search.set($any($event.target).value)" (keyup.enter)="apply()"></label><select class="rounded-xl border border-border px-4 py-3" aria-label="Technology" [value]="technology()" (change)="technology.set($any($event.target).value);apply()"><option value="">All technologies</option>@for(item of technologies();track item.id){<option [value]="item.name">{{item.name}}</option>}</select><select class="rounded-xl border border-border px-4 py-3" aria-label="Sort" [value]="sort()" (change)="sort.set($any($event.target).value);apply()"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="title">Title</option></select><button class="rounded-xl bg-primary px-5 py-3 font-bold text-white" (click)="apply()">Apply</button></div>
@if(loading()){<div class="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">@for(item of [1,2,3,4,5,6];track item){<div class="h-96 animate-pulse rounded-[20px] bg-slate-200"></div>}</div>}@else if(error()){<div class="mt-8 rounded-2xl border border-red-200 bg-red-50 p-10 text-center"><h2 class="text-xl font-bold text-red-900">Projects are temporarily unavailable</h2><p class="mt-2 text-sm text-red-700">{{error()}}</p><button class="mt-5 rounded-xl border border-red-300 px-5 py-2 font-semibold text-red-800" (click)="load()">Try again</button></div>}@else if(!items().length){<div class="mt-8 rounded-2xl border border-dashed border-border bg-white p-12 text-center"><h2 class="text-xl font-bold">No matching projects</h2><p class="mt-2 text-muted">Try a broader search or clear the technology filter.</p><button class="mt-5 rounded-xl bg-primary px-5 py-2 font-semibold text-white" (click)="clear()">Clear filters</button></div>}@else{<div class="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">@for(project of items();track project.id){<app-project-card [project]="project"/>}</div><nav class="mt-10 flex items-center justify-between" aria-label="Projects pagination"><p class="text-sm text-muted">Page {{page()}} of {{totalPages()||1}}</p><div class="flex gap-2"><button class="rounded-xl border border-border bg-white px-4 py-2 font-semibold disabled:opacity-40" [disabled]="page()<=1" (click)="changePage(page()-1)">Previous</button><button class="rounded-xl border border-border bg-white px-4 py-2 font-semibold disabled:opacity-40" [disabled]="page()>=totalPages()" (click)="changePage(page()+1)">Next</button></div></nav>}</section>`})
export default class ProjectsListComponent{private readonly api=inject(ProjectsApiService);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly destroyRef=inject(DestroyRef);readonly items=signal<ProjectListItem[]>([]);readonly technologies=signal<Technology[]>([]);readonly search=signal('');readonly technology=signal('');readonly sort=signal('newest');readonly page=signal(1);readonly totalPages=signal(0);readonly loading=signal(true);readonly error=signal<string|null>(null);
constructor(){this.api.technologies().pipe(takeUntilDestroyed()).subscribe({next:x=>this.technologies.set(x)});this.route.queryParamMap.pipe(takeUntilDestroyed()).subscribe(params=>{this.search.set(params.get('search')||'');this.technology.set(params.get('technology')||'');this.sort.set(params.get('sort')||'newest');this.page.set(Math.max(1,Number(params.get('page'))||1));this.load()})}
load(){this.loading.set(true);this.error.set(null);this.api.list({search:this.search(),technology:this.technology(),sort:this.sort(),page:this.page(),pageSize:9}).pipe(finalize(()=>this.loading.set(false)),takeUntilDestroyed(this.destroyRef)).subscribe({next:r=>{this.items.set(r.items);this.totalPages.set(r.totalPages)},error:()=>this.error.set('Check your connection and try again.')})}
apply(){this.navigate(1)}changePage(page:number){this.navigate(page)}clear(){this.search.set('');this.technology.set('');this.sort.set('newest');this.navigate(1)}private navigate(page:number){this.router.navigate([],{relativeTo:this.route,queryParams:{search:this.search()||null,technology:this.technology()||null,sort:this.sort()==='newest'?null:this.sort(),page:page===1?null:page}})} }
