<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design"><PrivateAssets>all</PrivateAssets></PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <ProjectReference Include="../Portfolio.Application/Portfolio.Application.csproj" />
    <ProjectReference Include="../Portfolio.Domain/Portfolio.Domain.csproj" />
    <ProjectReference Include="../Portfolio.Shared/Portfolio.Shared.csproj" />
  </ItemGroup>
</Project>
