import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { ProjectDraft, Technology } from '../../data-access/project.models';

@Component({ selector:'app-review-publish-step', changeDetection:ChangeDetectionStrategy.OnPush,
  template:`<section class="grid gap-5"><div><h2 class="text-xl font-semibold">Review and Publish</h2><p class="mt-1 text-sm text-muted-foreground">Check the project before making it publicly visible.</p></div>
    <div class="grid gap-4 sm:grid-cols-2"><article class="rounded-xl border border-border p-5"><p class="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Project</p><h3 class="mt-2 text-lg font-semibold">{{ draft().title || 'Untitled project' }}</h3><p class="mt-2 text-sm text-muted-foreground">{{ draft().shortDescription || 'No summary yet.' }}</p></article><article class="rounded-xl border border-border p-5"><p class="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Readiness</p><ul class="mt-3 grid gap-2 text-sm"><li [class.text-emerald-600]="draft().title">✓ Title</li><li [class.text-emerald-600]="draft().slug">✓ Slug</li><li [class.text-emerald-600]="draft().shortDescription">✓ Short summary</li></ul></article></div>
    <div class="grid gap-4 sm:grid-cols-3"><div class="rounded-xl bg-muted p-4"><strong class="block text-2xl">{{ selectedTechnologies().length }}</strong><span class="text-sm text-muted-foreground">Technologies</span></div><div class="rounded-xl bg-muted p-4"><strong class="block text-2xl">{{ draft().images.length }}</strong><span class="text-sm text-muted-foreground">Gallery images</span></div><div class="rounded-xl bg-muted p-4"><strong class="block text-2xl">{{ draft().links.length }}</strong><span class="text-sm text-muted-foreground">Links</span></div></div>
    @if (!ready()) {<div class="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900" role="alert">Complete the title, slug, and short summary before publishing.</div>}</section>` })
export default class ReviewPublishStepComponent { readonly draft=input.required<ProjectDraft>(); readonly selectedTechnologies=input<readonly Technology[]>([]); readonly ready=input(false); }
