import { ChangeDetectionStrategy, Component, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { AdminPageHeaderComponent } from '../../../../shared/components/admin-page-header/admin-page-header.component';
import { AdminStatus, AdminStatusBadgeComponent } from '../../../../shared/components/admin-status-badge/admin-status-badge.component';
import { AdminInfographicDetails, ContentStatus, difficultyLabel, statusLabel } from '../../data-access/infographic.models';
import { InfographicsApiService } from '../../data-access/infographics-api.service';
import { environment } from '../../../../../environments/environment';

@Component({selector:'app-infographic-details',imports:[RouterLink,AdminPageHeaderComponent,AdminStatusBadgeComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<app-admin-page-header title="Infographic Details" description="Review the operational content, media references, and publishing state." [breadcrumbs]="[{label:'Infographics',link:'/infographics'},{label:'Details'}]">
  <div adminPageActions class="flex flex-wrap gap-2">@if(item();as guide){@if(guide.status===1){<a class="kt-btn kt-btn-outline" [href]="publicUrl+'/visual-handbook/'+guide.slug" target="_blank" rel="noopener">View Live</a>}<a class="kt-btn kt-btn-primary" [routerLink]="['/infographics',guide.id,'edit']">Edit</a>}</div>
</app-admin-page-header>
@if(loading()){<div class="h-96 animate-pulse rounded-[20px] bg-muted"></div>}@else if(error()){<div class="rounded-2xl border border-red-300 p-10 text-center"><h2 class="font-semibold">Infographic could not be loaded</h2><p class="mt-2 text-sm text-muted-foreground">{{error()}}</p><button class="kt-btn kt-btn-outline mt-5" (click)="load()">Retry</button></div>}@else if(item();as guide){
<section class="overflow-hidden rounded-[20px] border border-border bg-background shadow-sm"><div class="grid gap-6 bg-gradient-to-r from-slate-950 to-indigo-950 p-6 text-white md:grid-cols-[1fr_280px] md:p-8"><div><div class="flex flex-wrap items-center gap-2"><app-admin-status-badge [status]="badge(guide.status)">{{status(guide.status)}}</app-admin-status-badge>@if(guide.isFeatured){<span class="rounded-full bg-amber-400/20 px-3 py-1 text-xs font-semibold text-amber-200">Featured</span>}</div><h1 class="mt-5 text-3xl font-bold">{{guide.title}}</h1><p class="mt-3 max-w-3xl text-sm leading-6 text-slate-300">{{guide.shortDescription}}</p></div><div class="grid min-h-40 place-items-center overflow-hidden rounded-2xl bg-white/10">@if(guide.coverUrl){<img [src]="guide.coverUrl" [alt]="guide.title" class="size-full object-cover">}@else{<i class="ki-filled ki-book-open text-6xl text-violet-300"></i>}</div></div>
<div class="grid gap-6 p-5 lg:grid-cols-[minmax(0,1fr)_320px] lg:p-8"><main class="grid gap-8"><section><h2 class="text-lg font-semibold">Overview</h2><p class="mt-3 whitespace-pre-line text-sm leading-7 text-muted-foreground">{{guide.description||'No introduction has been added.'}}</p></section><section><div class="flex items-center justify-between"><h2 class="text-lg font-semibold">Content Steps</h2><span class="text-sm text-muted-foreground">{{guide.steps.length}} steps</span></div><ol class="mt-4 grid gap-3">@for(step of guide.steps;track step.id){<li class="rounded-xl border border-border p-4"><div class="flex gap-3"><span class="grid size-8 shrink-0 place-items-center rounded-full bg-primary/10 font-bold text-primary">{{step.stepNumber}}</span><div><h3 class="font-semibold">{{step.title}}</h3><p class="mt-2 whitespace-pre-line text-sm leading-6 text-muted-foreground">{{step.content}}</p></div></div></li>}@empty{<li class="rounded-xl border border-dashed border-border p-6 text-sm text-muted-foreground">No content steps yet.</li>}</ol></section>
@if(guide.resources.length){<section><h2 class="text-lg font-semibold">Resources</h2><div class="mt-4 grid gap-2">@for(resource of guide.resources;track resource.id){<a [href]="resource.url" target="_blank" rel="noopener" class="flex items-center justify-between rounded-xl border border-border p-4 hover:border-primary"><span><strong class="block">{{resource.title}}</strong><span class="text-xs text-muted-foreground">{{resource.resourceType}}</span></span><i class="ki-filled ki-exit-up"></i></a>}</div></section>}
@if(guide.codeExamples.length){<section><h2 class="text-lg font-semibold">Code Examples</h2><div class="mt-4 grid gap-4">@for(example of guide.codeExamples;track example.id){<article class="overflow-hidden rounded-xl border border-border"><header class="flex items-center justify-between bg-muted px-4 py-3"><strong>{{example.title}}</strong><span class="text-xs uppercase text-muted-foreground">{{example.language}}</span></header><pre class="overflow-x-auto bg-slate-950 p-4 text-xs text-slate-100"><code>{{example.code}}</code></pre></article>}</div></section>}</main>
<aside class="self-start rounded-2xl border border-border bg-muted/20 p-5 lg:sticky lg:top-6"><h2 class="font-semibold">Information</h2><dl class="mt-4 grid gap-4 text-sm"><div><dt class="text-muted-foreground">Category</dt><dd class="mt-1 font-medium">{{categoryName(guide.categoryId)}}</dd></div><div><dt class="text-muted-foreground">Difficulty</dt><dd class="mt-1 font-medium">{{difficulty(guide.difficultyLevel)}}</dd></div><div><dt class="text-muted-foreground">Updated</dt><dd class="mt-1 font-medium">{{(guide.updatedAt||guide.createdAt).slice(0,10)}}</dd></div><div><dt class="text-muted-foreground">Tags</dt><dd class="mt-2 flex flex-wrap gap-1">@for(tag of guide.tags;track tag.id){<span class="rounded-full bg-background px-2 py-1 text-xs">{{tag.name}}</span>}</dd></div><div><dt class="text-muted-foreground">Media</dt><dd class="mt-1 text-xs">Cover: {{guide.coverUrl?'Available':'None'}}<br>Main image: {{guide.infographicUrl?'Available':'None'}}<br>PDF: {{guide.pdfUrl?'Available':'None'}}</dd></div>@if(guide.series.length){<div><dt class="text-muted-foreground">Series</dt><dd class="mt-2 grid gap-1">@for(series of guide.series;track series.id){<span>{{series.position}}. {{series.name}}</span>}</dd></div>}</dl></aside></div></section>}
`})
export default class InfographicDetailsComponent{
  private readonly api=inject(InfographicsApiService);private readonly route=inject(ActivatedRoute);private readonly destroyRef=inject(DestroyRef);readonly item=signal<AdminInfographicDetails|null>(null);readonly categories=signal<{id:string;name:string}[]>([]);readonly loading=signal(true);readonly error=signal<string|null>(null);readonly difficulty=difficultyLabel;readonly status=statusLabel;readonly publicUrl=environment.publicWebUrl;
  constructor(){this.api.categories().pipe(takeUntilDestroyed()).subscribe({next:x=>this.categories.set(x)});this.load()}
  load(){this.loading.set(true);this.error.set(null);this.api.get(this.route.snapshot.paramMap.get('id')!).pipe(finalize(()=>this.loading.set(false)),takeUntilDestroyed(this.destroyRef)).subscribe({next:x=>this.item.set(x),error:e=>this.error.set(e?.error?.detail||'Check the API and try again.')})}
  badge(value:ContentStatus):AdminStatus{return value===0?'draft':value===1?'published':'archived'}categoryName(id:string){return this.categories().find(x=>x.id===id)?.name||'Category'}
}
